gradido/gradido

- .github/workflows/test.yml
- frontend/.babelrc
- frontend/.gitignore
- frontend/package.json
- frontend/src/components/CloseButton.spec.js
- frontend/test/registerContext.js
- frontend/yarn.lock
Setting up the unit tests for the frontend
> Setup unit tests for frontend

- frontend/src/config/index.js
- frontend/src/store/store.js
- frontend/src/views/KontoOverview/GddTable.vue
- correctly use envs to query transactions
- Cleanups
- relates #52
> Correctly use transactions API in frontend

- frontend/src/views/KontoOverview/GddSend.vue
> fix-padding

- frontend/src/views/Layout/ContentFooter.vue
Localize the links to gradido.net accordind to the active locale.
- fixes #58
> feat: Localize links to gradito.net

- frontend/package.json
- frontend/src/App.vue
- frontend/src/i18n.js
- frontend/src/locales/en.json
- frontend/src/main.js
- frontend/src/vee-validate.js
- frontend/src/views/Layout/AuthLayout_gdd.vue
- frontend/src/views/Layout/ContentFooter.vue
- frontend/yarn.lock
Validation messages are translated to German now.
- fixes #60
Check if we also have to translate certain field-names (e.g. Password vs. Passwort)
> feat: Lokalize Validation Messages

- login_server/src/cpp/JSONInterface/JsonGetUserInfos.cpp
fix bug with access rights which prevent sending gradidos
> fix bug with access rights

- frontend/src/apis/communityAPI.js
- frontend/src/config/index.js
- frontend/src/store/store.js
- correct send api
- correct send URL env variable
- None
> use_correct_send_api

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Layout/DashboardLayout.vue
Added some missing locales and improved translations
> feat: improve translations

- frontend/src/store/store.js
- frontend/src/views/KontoOverview/GddAddWork2.vue
- frontend/src/views/KontoOverview/GddSend.vue
- frontend/src/views/KontoOverview/GddStatus.vue
- frontend/src/views/KontoOverview/GddTable.vue
- frontend/src/views/KontoOverview/GddWorkTable.vue
- frontend/src/views/Pages/UserProfileActivity.vue
frontend/src/views/KontoOverview/GddTable.vue  
die reinfolge der tranactionen sind jetzt datum DESC
> New fix up frontend for presentation

- frontend/src/store/store.js
- frontend/src/views/KontoOverview/GddAddWork2.vue
- frontend/src/views/Pages/UserProfileActivity.vue
> activity page stap 2

- docu/login_server.api.md
- login_server/src/cpp/JSONInterface/JsonCheckSessionState.cpp
- login_server/src/cpp/JSONInterface/JsonCheckSessionState.h
- login_server/src/cpp/JSONInterface/JsonRequestHandlerFactory.cpp
add function to login server api to check if session is valid
> add check session state json function and doc

- docu/login_server.api.md
update mardown of login server api
> markdown of login server api

- login_server/Dockerfile
- login_server/Dockerfile.debug
- login_server/Dockerfiles/Dockefile.protoc
- login_server/Dockerfiles/Dockerfile.dependencies
- login_server/Dockerfiles/Dockerfile.protoc
Now login-server use protoc and his other dependencies from prebuild and to docker hub uploaded images.
- Slow Build on Test
- Now the build-time on github is similar to the build-time from frontend
> Optimize login server build

- login_server/src/cpp/SingletonManager/EmailManager.cpp
I think I have at last found the reason why sometime no emails are sended by login-server on production server. 
Every time someone use a email address with non existence domain, the email sending throw a exception which was catched in my thread function, ending the email-sending-thread. 
Now I catch the assert earlier so email-thread should stil work after exception.
#133
> at last, fix email-bug

- docker-compose.override.yml
- docker-compose.yml
- frontend/vue.config.js
- login_server/Dockerfile.debug
- login_server/Dockerfiles/build_and_run.sh
- login_server/src/cpp/Gradido_LoginServer.cpp
- nginx/nginx.conf
in frontend 
depends_on:
- nginx
leads to circular dependencie because nginx depens_on frontent. 
Removed it.
By the way add debug message to Login-Server after he starts visible also in docker. 
Make VUE_PATH default to /vue and copy back vue changes in nginx.conf so that on default composer-build
the new client is reachable with http://localhost/vue
> Fix compose bug

- docker-compose.yml
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/test/testSetup.js
Testing the layout of the Dashboard.
> feat: Test Dashboard Layout

- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/store/store.js
- frontend/src/views/Layout/ContentFooter.vue
- frontend/src/views/Layout/DashboardLayout_gdd.vue
in the footer of the app the link to the elopage community has been added
#125
> fix-125-link-to-community

- docu/userstorry_button.txt
erstellen einer userstorry_button
> userstorry_button.txt example

- docu/README.md
- docu/login_server.api.md
> documentation for reset password

- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/routes/router.js
- frontend/src/views/KontoOverview/GddSend.vue
- frontend/src/views/Layout/ContentFooter.vue
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- nginx/nginx.conf
* setting `mode: 'history'` to avoid # in routes (see Todo)
* added some missing locales (members area)
* changed locale of members area
* removed use of store in Send compoenent
- relates #104
> fix: Remove Hashtag From Route

- frontend/jest.config.js
- frontend/package.json
- frontend/src/views/KontoOverview.spec.js
- frontend/src/views/KontoOverview/GddStatus.spec.js
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/test/testSetup.js
- frontend/yarn.lock
> feat: Unit Test for KontoOverview

- .github/workflows/test.yml
remove coverage report since its very spammy
- None
> coverage_no_report

- login_server/src/cpp/model/table/PendingTask.cpp
fix crash occuring by successful transfered transactions
> Login 14.04.21

- .github/workflows/test.yml
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/Register.spec.js
- frontend/src/views/Pages/Register.vue
Die registrierung kann erst abgeschich werden wenn:
- firstname  (lenght min 3)
- lastname (lenght min 2)
- email
- password  
1. Ein Kleinbuchstabe erforderlich.
2. Ein Großbuchstabe erforderlich.
3. Mindestens 8 Zeichen.
4. Eine Zahl erforderlich.
- datenschutzbestimmung zugestimmt wurde
- fixes #30
> fix register

- login_server/src/cpp/SingletonManager/PendingTasksManager.cpp
> update code which produce error which last fix (._.);

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Layout/ContentFooter.spec.js
- frontend/src/views/Layout/ContentFooter.vue
> feat: Link to Whitepaper in Content-Footer

- .github/workflows/publish.yml
- .github/workflows/test.yml
- login_server/Dockerfile
refactor workflows
- adjust names
- publish community_server
- publish login_server
- test build & publish nginx
- test build & publish mariadb
- fixes #46 
- fixes #92
> workflows_refactor

- docker-compose.override.yml
removed community_server volume
- None
> fix_docker_compose

- .github/workflows/test.yml
You need 12% test coverage in frontend now.
> feat: Raise Frontend Test Coverage to 12%

- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/routes/routes.js
- frontend/src/views/Layout/DashboardNavbar.vue
rechtes menü habe ich entfernt
- fixes #179
> refactor: Remove Right Menu

- frontend/src/views/Pages/Login.spec.js
- frontend/src/views/Pages/Login.vue
No rules for the password field on login. The rules are set in register or reset password.
- fixes #190
> fix: Remove Rules for Password on Login

- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/store/store.js
- frontend/src/views/Layout/DashboardLayout_gdd.vue
- frontend/src/views/Layout/DashboardNavbar.vue
Now all API calls to the login_server are removed from the store. They are all in the correspondent components, so we can do a proper error handling if a call fails. 
- fixes #211
> refactor: Remove loginAPI Call from Store

- docker-compose.override.yml
- docker-compose.yml
- docu/login_server.api.md
- login_server/Dockerfile.debug
- login_server/Dockerfiles/build_and_run.sh
- login_server/src/cpp/JSONInterface/JsonCreateUser.cpp
Build Login-Server complete after docker-compose up in a volume
use Login-Server src from filesystem not docker
use Community-Server src from filesystem not docker 
add default group_id = 1 and give information if group_id isn't set
update Login-Server api doc to add group_id
> update login-server build

- community_server/src/Controller/AppRequestsController.php
- docker-compose.override.yml
- frontend/src/apis/communityAPI.js
- login_server/Dockerfile.debug
- login_server/Dockerfiles/build_and_run.sh
- login_server/src/cpp/model/Session.cpp
Using again prebuild dependencies in docker image, 
but keep mounted /src from login-server and community-server for easyer update on changes
> Rollback use prebuild dependencies

- login_server/src/cpp/JSONInterface/JsonUnsecureLogin.cpp
Since stage2 users belong to a group. 
But until now unsecureLogin cannot handle this state. 
I have changed it now. Now if group_id from user is 0, it will be set to 1
Additional I have added a error message if user state has an unknown value.
> fix empty reply by empty group_id

- frontend/src/views/KontoOverview/GddSend.vue
- frontend/src/views/Pages/Register.vue
Clicks on button gelegt
- pwd anzeigen / verstecken
- cancel qrcode scan
- #239 
- #247
> Clicks on button

- docu/community-server.api.md
> add short description for target date in creation transaction

- docu/login_server.api.md
- login_server/src/cpp/model/table/User.cpp
with unsecureLogin and loginViaEmailVerificationCode language will be returned as additional user field
- relates #209
> add language as fields which will be returned with user-object

- .github/workflows/test.yml
require 13% coverage
(We are at ~13.5%, therefore this should be save and have enough margin to not fail immediately)
- None
> 13_coverage

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/devops_ticket.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/refactor_tickets.md
rework issue templates since "humanconnection" string was still present, simplified all templates while doing this
- None
> fix_issue_templates

- frontend/package.json
- frontend/src/plugins/dashboard-plugin.js
- frontend/src/views/Layout/AuthLayout_gdd.vue
- frontend/src/views/Pages/Login.vue
- frontend/yarn.lock
spinner an der componente .. variante 2
- fixes #243
> 243 vue loader component - varante 2

- skeema/Dockerfile
<!-- Which Issues does this fix, which are related?
- fix error by updating db schema
> update skeema call to allow also for unsafe db updates

- community_server/src/Controller/AppController.php
@Mogge Magst du es damit nochmals teste bitte?
- None
> change order of session_id

- frontend/src/routes/routes.js
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/src/views/Layout/DashboardLayout_gdd.vue
remove menu lnk to not work in this version 
- #265
> remove links to not work

- .github/workflows/test.yml
- frontend/src/store/store.js
- frontend/src/store/store.test.js
- frontend/src/views/KontoOverview/GddStatus.spec.js
- frontend/src/views/KontoOverview/GddStatus.vue
- frontend/src/views/KontoOverview/GddTable.vue
- frontend/src/views/Layout/DashboardLayout_gdd.vue
- frontend/src/views/Pages/KontoOverview.vue
- frontend/src/views/Pages/Register.vue
* GDT balance is no longer stored in store. It is a property of the DashboardLayout (as balance)
* Testing the store
* As create user and login do the same, just login is used.
* Coverage to 15%
> refactor: Test and Clean Up Store

- frontend/src/views/Pages/UserProfile/UserCard.vue
- frontend/src/views/Pages/UserProfileCard.vue
The user profile tried to get the balance from the store. Now it is a property.
> fix: Dynamic Balance in User Profile

- .github/ISSUE_TEMPLATE/bug_report.md
fixed bug_report.md issue template - comment not closed
- None
> fix_bug_template

- login_server/src/cpp/JSONInterface/JsonUnsecureLogin.cpp
Have found a little bug on this branch
> fix bug on Login group add host

- frontend/src/views/NotFoundPage.vue
> xx deleted

- community_server/src/Model/Transactions/TransactionTransfer.php
> remove  from error messages because its no longer exist

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/AccountOverview/GddSend.spec.js
- frontend/src/views/Pages/AccountOverview/GddSend.vue
send formular geändert
- cancel button zu "reset" button in deutsch "zurücksetzen"
- reset form event an button 
- fixes #291
> cancel to reset, form rest event added

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/Register.vue
error messages are displayed
the error transferred from the backend is displayed 1:1 in the error field. 
- fixes #240
> error messages are displayed

- frontend/src/apis/communityAPI.js
Set defaults for API call listTrandsctions. Order is changed by default to DESC
- relates #328
> refactor: Add Paramerts to ListTransactions API Call

- frontend/src/locales/en.json
in en.json "transaction.show_all" hinzugefügt
- fixes #326
> transaction.show_all in en.json hinzugefügt

- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/src/views/Layout/DashboardLayout_gdd.vue
im menu ist "min profil" momentan auskommentiert
- fixes #283
> my profile auskommentiert

- frontend/src/views/Pages/AccountOverview.vue
abstand im header angepasst
- fixes #338
> 338 - mt-5 margin top 5 eingebunden

- community_server/src/Model/Table/TransactionsTable.php
> don't show decays smaller than 0,01 GDD

- frontend/src/main.js
- frontend/src/store/store.js
- frontend/src/store/store.test.js
- frontend/src/views/Layout/DashboardLayout_gdd.vue
- frontend/src/views/Pages/AccountOverview/GddSend.vue
- frontend/src/views/Pages/Login.vue
- frontend/src/views/Pages/Register.vue
- frontend/src/views/Pages/ResetPassword.vue
Implementing the eslint standard rules caused some bugs. They are fixed.
> bug: session_id vs sessionId

- frontend/src/views/NotFoundPage.vue
404 seite linkweiterleitung zu login fehler behoben
> 404 link to login page fix

- frontend/src/views/Pages/ResetPassword.vue
das click event vom icon auf den button gelegt
- fixes #351
> clickevent from icon to button

- frontend/src/components/SidebarPlugin/SideBar.vue
members area open in a new tab
teil von #350
> fix: membersarea open in a new tap

- frontend/src/views/Layout/ContentFooter.spec.js
- frontend/src/views/Layout/ContentFooter.vue
- frontend/src/views/Pages/AccountOverview/GddStatus.vue
Support link im footer eingebaut, der link verlässt momentan die app
- fehler gefixt .. "col" error
- fixes #233
> 233-Support-Button fix, and col error fix

- frontend/src/views/Pages/AccountOverview/GddSend.spec.js
- frontend/src/views/Pages/AccountOverview/GddSend.vue
change design- dark-blue of text-ligth
teil von: #350
> change design- dark-blue of text-ligth

- frontend/src/views/Pages/AccountOverview/GddSend.vue
QR Scanner ist für die aktuelle version abgestellt. 
teil von: #350
> Fix: QR Scanner Hide

- docu/other/mariadb_groups_insert.md
eine dokumentation zum localen schöpfen.
> docu: locales schöpfen-mysql befehl

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/AccountOverview/GddSend.vue
- eine error message wird angezeigt wenn transaction fehl schlägt. (wie success message)
- englische übersetzungen was deutsch war 
- fixes #107
> transaction error message, translations

- login_server/src/cpp/JSONInterface/JsonCreateUser.cpp
- login_server/src/cpp/JSONInterface/JsonRequestHandler.cpp
- login_server/src/cpp/JSONInterface/JsonRequestHandler.h
- login_server/src/cpp/JSONInterface/JsonSendEmail.cpp
- login_server/src/cpp/controller/EmailVerificationCode.cpp
If frontend.checkEmailPath is set, use it as correct as base Path for checkEmailCode links
> fix link generation

- frontend/src/views/Pages/Register.vue
- frontend/src/views/Pages/ResetPassword.vue
translation password rules in Register.vue and ResetPasswort.vue fixed
- fixes #408
> translation password rules in Register.vue and ResetPasswort.vue fixed

- frontend/src/views/Pages/thx.vue
thx.vue coloured background removed. design adapted to app
- fixes #402
> thx.vue coloured background removed. design adapted to app

- .github/workflows/test.yml
> feat: Raise Coverage of Frontend Unit Tets to 18%

- community_server/src/Model/Table/TransactionsTable.php
- community_server/src/Template/AppRequests/list_transactions.ctp
- community_server/src/Template/Element/centToFloat.ctp
call ceil instead of floor by the last decay.. the decay from last transaction to now. 
- fixes #434 
- relates #439
> ceil the last decay

- community_server/src/Controller/AppRequestsController.php
- community_server/src/Controller/JsonRequestHandlerController.php
- community_server/src/Model/Transactions/Transaction.php
- community_server/src/Model/Transactions/TransactionBase.php
- community_server/src/Model/Transactions/TransactionCreation.php
- community_server/src/Model/Transactions/TransactionTransfer.php
- community_server/src/Template/Email/text/notification_transaction_failed.ctp
send user a email if his transaction failed
- fixes #362
> add dynamic error email if transaction failed

- frontend/src/views/Pages/Login.vue
login password change show hide inserted
- fixes #431
> bug-login password change show hide inserted

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/AccountOverview.vue
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionConfirmation.vue
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.spec.js
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue
attention! notice in send area removed, in locales remove
- fixes #433
> attention! notice in send area removed

- .github/workflows/test.yml
- frontend/src/apis/loginAPI.js
- frontend/src/components/LanguageSwitch.spec.js
- frontend/src/components/LanguageSwitch.vue
- frontend/src/components/SidebarPlugin/SideBar.spec.js
- frontend/src/locales/index.js
- frontend/src/store/store.js
- frontend/src/store/store.test.js
- frontend/src/views/Layout/ContentFooter.spec.js
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/src/views/Pages/Login.spec.js
- frontend/src/views/Pages/Login.vue
- frontend/src/views/Pages/Register.spec.js
Saves the locale when changed and a session_id is available in the database.
- fixes #353 
- fixes #209
> feat: Save Locale in Database

- frontend/src/locales/de.json
[Bug] German "Dir" is written with capital D in send validation bug
#403  opened 7 days ago by ulfgebhardt
🏃21/05 May
- fixes #403
>  [Bug] German "Dir" is written with capital D in send validation bug

- frontend/src/views/Layout/DashboardNavbar.vue
- frontend/src/views/Pages/AccountOverview.spec.js
- frontend/src/views/Pages/AccountOverview.vue
bug: responsive display error on pads fixed
- fixes #457
> bug: responsive display error on pads fixed

- login_server/src/cpp/SingletonManager/PendingTasksManager.cpp
Login-Server crashes sometime on production server,
so everytime I found and possible reason for it I fix it in this branch.
- relates #293
> everything I find and fix crash related in login server this week (kw 20)

- frontend/src/i18n.js
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionConfirmation.vue
- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
Use vue-i18n dateTimeFormats to display date and time. Time is displayed in timezone of user.
- fixes #299
> fix: Date Time Formats

- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/i18n.js
- frontend/src/views/Pages/AccountOverview/GddStatus.vue
- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
- frontend/src/views/Pages/UserProfile/UserCard.vue
Introduced decimal number format, removed currency number format.
> fix: GDD Amount is Always Displayed with Two Digits

- login_server/CMakeLists.txt
fixed problem with finding cpsp parse binary under windows with conan
> fixed problem with finding cpsp parse binary under windows with conan

- frontend/src/config/index.js
reads the version number from package.json and adds it to the CONFIG object.
- fixes #401
> fix: Show Correct Version Number in Footer

- login_server/src/cpp/model/table/User.cpp
By adding description and username to user table I have forgetten to add enough ? as placeholder for insert into table call.
> fix problem with create User

- frontend/src/apis/loginAPI.js
- frontend/src/views/Layout/DashboardLayout_gdd.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.vue
fix bugs 
- fixes #508 #507 #505 #504
> Feature  profile page bugs

- frontend/src/apis/loginAPI.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.vue
> Feature  profile page userdata css

- community_server/src/Controller/AppRequestsController.php
- frontend/src/views/Pages/AccountOverview.vue
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionConfirmation.vue
- frontend/src/views/Pages/UserProfile.spec.js
Allow to call sendCoins without target_date
> fix: Remove Target Date in Send Coins Request

- community_server/src/Model/Table/TransactionsTable.php
- remove check decays for being at least 100 GDD cent
- remove debugging lines and empty lines
For the reason see  #439
- fixes #439
> remove check decays for being at least 100 GDD cent

- frontend/src/main.js
* no digits after period or comma is allowed
*  localize numbers in vaidation message
> fix: Validation of GDD Send Amount Field

- .github/workflows/test.yml
- frontend/src/apis/loginAPI.js
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/main.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.vue
* Username can only be changed when no username is given
* Username must start with a letter
* Username must have at least three alphanumeric characters
* Username must be unique
- relates #532
> feat: Validate Change Username

- .github/workflows/test.yml
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/src/views/Pages/ForgotPassword.spec.js
- frontend/src/views/Pages/ForgotPassword.vue
- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/ResetPassword.vue
- frontend/test/testSetup.js
* remove router from test setup
* fix testing problems with router
* add test for forget password
- None
> feat: Test Forget Password

- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
button defauflt hebt sich mehr ab, rules am passwird change disable butten 
- fixes #541
> change userdata button disable rules

- .github/workflows/test.yml
- frontend/src/apis/loginAPI.js
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Layout/DashboardLayout_gdd.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
* alerts removed
* logic improved
^ remove API call on transaction list after login
> fix: Change Password Form

- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.spec.js
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue
- frontend/src/views/Pages/AccountOverview/GddStatus.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
> Mobile UI send gdd form

- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue
Trims the email of the GDD send form after loosing focus.
> feat: Trim Email on Blur

- frontend/src/views/Pages/AccountOverview/GddSend/TransactionResult.vue
> fix to big text ths

- .github/workflows/test.yml
- community_server/src/Controller/AppController.php
- community_server/src/Model/Table/TransactionsTable.php
- community_server/tests/TestCase/Controller/AppRequestControllerTest.php
- login_server/src/cpp/JSONInterface/JsonGetLogin.cpp
- login_server/src/cpp/JSONInterface/JsonRequestHandlerFactory.cpp
- login_server/src/cpp/SingletonManager/PendingTasksManager.cpp
- login_server/src/cpp/SingletonManager/PendingTasksManager.h
- login_server/src/cpp/SingletonManager/SessionManager.cpp
- login_server/src/cpp/lib/MultithreadContainer.h
- login_server/src/cpp/model/Session.cpp
- login_server/src/cpp/model/gradido/Transaction.cpp
- login_server/src/cpp/model/table/ModelBase.cpp
- login_server/src/cpp/model/table/PendingTask.cpp
- show in between decays only if <= 0.01 GDD
- None
> hot fixes shown by test

- frontend/src/apis/loginAPI.js
> fix: API Call for Reset Password

- frontend/src/main.js
> fix: Remove Grouping for Max Error

- login_server/src/cpp/model/gradido/Transaction.cpp
- login_server/src/cpsp/CheckTransaction.cpsp
fix problems with pending transactions 
- fix problem with failed and not deleted transaction occuring again and again
- fix problem with from user aborted transactions
- fixes #577 
- fixes #563
> Login fix pending transactions

- login_server/src/cpp/JSONInterface/JsonGetUsers.cpp
- login_server/src/cpp/controller/User.cpp
- login_server/src/cpp/test/JSONInterface/TestJsonGetUsers.cpp
- login_server/src/cpp/test/main.cpp
Error occure because model::table::UserTuple has changed. Description was added, so I must update the custom mysql query for the search also.
- fixes #575
> update mysql because tuple has changed

- deployment/bare_metal/build_and_start_login_server.sh
- deployment/bare_metal/build_frontend.sh
- deployment/bare_metal/nginx/sites-available/gradido
- deployment/bare_metal/nginx/sites-available/gradido_updating
- deployment/bare_metal/nginx/updating_original.html
- deployment/bare_metal/update_all.sh
- deployment/bare_metal/update_db_schemas.sh
Scripts for auto-deploy on bare metal
- fixes #560
> Auto deploy

- docker-compose.override.yml
- login_server/Dockerfiles/ubuntu/Dockerfile.debug
switch to login-server running in ubuntu container
because alpine container crash without reason
Login-Server crashes by sending transaction or if a pending-transaction is in db
> Fix crashing Problem with Login-Server

- .github/workflows/test.yml
- frontend/src/store/store.test.js
> refactor: Update Store Tests

- frontend/src/views/Pages/ForgotPassword.spec.js
- frontend/src/views/Pages/ForgotPassword.vue
> refactor: Forgot Password Form

- .github/workflows/test.yml
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/main.js
- frontend/src/views/Pages/Login.spec.js
- frontend/src/views/Pages/Login.vue
- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/ResetPassword.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.spec.js
> refactor: Reset Password Page

- .github/workflows/test.yml
- frontend/src/components/Inputs/InputPasswordConfirmation.spec.js
- frontend/src/main.js
- frontend/src/plugins/dashboard-plugin.js
- frontend/src/validation-rules.js
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.spec.js
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue
- frontend/src/views/Pages/ForgotPassword.spec.js
- frontend/src/views/Pages/Login.spec.js
- frontend/src/views/Pages/Register.spec.js
- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.spec.js
- frontend/test/testSetup.js
Tests the validation rules when applied in the components.
> feat: Test Validation Rules

- .github/workflows/test.yml
- frontend/src/views/Pages/AccountOverview.spec.js
- frontend/src/views/Pages/AccountOverview.vue
- frontend/src/views/Pages/AccountOverview/GddStatus.vue
> feat: Test AccountOverview

- frontend/src/components/PaginationButtons.vue
> fix: Mobile Pagination

- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> fix: Transaction Pagination Scroll Top

- frontend/src/views/Pages/AccountOverview/GddTransactionList.spec.js
window.scrollTo was not mocked.
> fix: Test for ScrollTo in Transaction List

- frontend/src/components/DecayInformation.vue
use computed value instead data to avoid looping.
> fix: Fix Infinite Loop in Transaction List

- frontend/src/views/Layout/DashboardLayout_gdd.vue
> fix: QRCode Error after Logout

- frontend/src/views/Pages/UserProfileTransactionList.spec.js
- frontend/src/views/Pages/UserProfileTransactionList.vue
> feat: Test UserProfileTransactionList

- frontend/package.json
- frontend/src/App.vue
- frontend/src/plugins/dashboard-plugin.js
- frontend/src/views/Pages/Login.spec.js
- frontend/src/views/Pages/Login.vue
- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/ResetPassword.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.vue
- frontend/yarn.lock
Use vue-toastes https://www.npmjs.com/package/vue-toasted instead of vue-bootstrap-toasts.
- fixes #596
- fixes #595
> refactor: Use Vue-Toasted to Toast Messages

- community_server/src/Template/AppRequests/list_transactions.ctp
Type of transaction should always be set,
but make sometimes a error.
So I change code that instead of invalid json a regular error will be returned.
> fix type not found error in listTransaction Call

- login_server/src/cpp/SingletonManager/PendingTasksManager.cpp
add check for user role in function for check for pending transactions some must sign.
- fixes #626
> fix bug with user roles and pending transactions

- community_server/src/Controller/AppRequestsController.php
The boolena controlling if first transaction will be skipped gets the wrong value by DESC ordering,
I've fixed it. 
- fixes #629
> fix last Transaction are not shown in new frontend 

- login_server/src/cpp/HTTPInterface/PageRequestHandlerFactory.cpp
- login_server/src/cpp/model/Session.cpp
- Fix wrong email link if register on old backend
- fix additional bug found by testing related with checkEmail
- fixes #638
> Login fix wrong check email link 

- login_server/src/cpp/model/email/Email.cpp
Make E-Mail Text for password reset E-Mail 100% German
> Make E-Mail Text 100% German

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/AccountOverview.spec.js
- frontend/src/views/Pages/AccountOverview.vue
- frontend/src/views/Pages/AccountOverview/GddSend/TransactionResult.vue
error message if no receiver is found
https://user-images.githubusercontent.com/1324583/126035824-09ee31c9-b028-463f-a7e6-d184ceea9734.mp4
- fixes #435 
- fixes #420
> #435 Visual Feedback on not sending GDD

- community_server/src/Controller/StateBalancesController.php
Take decay from transaction and make a transaction from it, following the transaction in which it came for old frontend. 
So the decay transaction are visible in old frontend.
- fixes #655
[ ] Test together with #652
> move back decay as standalone transaction in old frontend

- community_server/db/setup_db_tables/insert_migrations.sql
update initial db data set 
- fixes #653
> fix unneccessary migration run on fresh (docker) setup

- community_server/src/Controller/StateBalancesController.php
> exchange positions of decay in transaction in old frontend

- frontend/src/views/Layout/DashboardLayout_gdd.vue
the main content now has a maximum width of 1000px
- fixes #680
https://user-images.githubusercontent.com/1324583/127020873-855542e0-fbc8-444f-aa4a-9f19f9c11a60.mp4
> 680 app large maximum width

- frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue
- text in the news box resized like the others
- font size changes when you focus an input field
- fixes #676 
https://user-images.githubusercontent.com/1324583/126771482-d476642e-8508-4c00-bec3-38ded7d7c3bf.mp4
> text-size in textarea and font-variante if focus

- frontend/src/App.vue
- frontend/src/components/Inputs/InputEmail.vue
- frontend/src/components/Inputs/InputPassword.vue
- frontend/src/components/Inputs/InputPasswordConfirmation.vue
- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/views/Pages/Register.spec.js
- frontend/src/views/Pages/Register.vue
- frontend/src/views/Pages/ResetPassword.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
> Css color input error

- .github/workflows/test.yml
> increase coverage to 34%

- backend/src/graphql/resolvers/TransactionResolver.ts
Use the createTransaction API Call from Login-Server for sendCoins directly rather than using Community-Server for tunneling,
> Apollo sendCoins via Login-Server

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
bug is fixed
I have also made text changes to the transactions in the infobox.
- fixes #708
> fix bug, change statment from transaction infbox

- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
- frontend/src/views/Pages/AccountOverview/GdtTransactionList.vue
adds pagination buttons to GDT transaction list
> feat: Add Pagination Buttons to GDT Transaction List

- community_server/src/Controller/AppRequestsController.php
Update parameter calculation to get correct number of asked transactions decay for all included
- fixes #721
> update code for correct transactions listening

- docu/other/fragen-community.md
Questions regarding Community - to have it documented in the Repo aswell.
- None
> Docu fragen community

- frontend/src/views/Pages/Login.vue
Corrects the login call so that it does not use the cached data anymore
- Fixes: https://github.com/gradido/gradido/issues/735
> Added a fetchPolicy: 'no-cache' to the login vall.

- backend/src/config/index.ts
bugfix:  change default value of communty url
- None
> change default value of communty url

- .github/ISSUE_TEMPLATE/release.md
New issue type Release - this was suggested by @clauspeterhuebner 
- None
> issue_type_release

- backend/src/graphql/models/GdtEntry.ts
- frontend/src/graphql/queries.js
- frontend/src/views/Pages/AccountOverview/GdtTransactionList.vue
- I have fixed the id in gdt server and add id for gdt in backend and frontend. 
- I fixed also a bug with icons in frontend, which lead to not showing my gdt transactions at all
- fixes #740
> Fix missing gdt id

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/Register.spec.js
- frontend/src/views/Pages/Register.vue
when a new registration at Gradido, the new member can choose the language. this also affects the newsletter.  
- fixes #185
> select language during registration

- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
Remove async for test. Hopefully this makes the test stable.
- fixes #772
> fix: Flaky Test for Logout

- community_server/src/Template/StateBalances/overview_gdt.ctp
By Event GDT Transaction old frontend is showing Euro instead of GDT.
I've fixed it.
> fix old frontend wrong display of event gdt

- configs/login_server/grd_login.properties
- login_server/src/cpp/JSONInterface/JsonSendEmail.cpp
- login_server/src/cpp/ServerConfig.cpp
- login_server/src/cpp/ServerConfig.h
- add additional path (url in new frontend) for resetPassword email
> different path for checkEmail and resetPassword

- community_server/src/Template/StateBalances/overview_gdt.ctp
GDT now return every gdt and euro amount as float instead of integer cent.
But I have another place found which I need to adjust to that new behaviour.
> fix euro after comma gdt view

- .github/workflows/test.yml
- frontend/src/components/PaginationButtons.spec.js
- frontend/src/components/PaginationButtons.vue
- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
- frontend/src/views/Pages/AccountOverview/GdtTransactionList.spec.js
- frontend/src/views/Pages/AccountOverview/GdtTransactionList.vue
* put all the logic in the pagination buttons
* adopt property names to bootstrap vue pagination buttons (if we should decide to use them)
* change setup for API calls, that change to bootstrap vue pagination buttons is easy to handle
- fixes #738
> refactor: Pagination Buttons

- README.md
> Remove discord link

- docu/Concepts/Snippets/Authorization/concept.md
- docu/Concepts/Snippets/Authorization/jwt.md
- docu/Concepts/Snippets/Authorization/session_id.md
How we could use JWT even without Login-Server.
> My thoughts to jwt

- frontend/src/components/SidebarPlugin/SideBar.spec.js
- frontend/src/components/SidebarPlugin/SideBar.vue
- frontend/src/graphql/mutations.js
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/store/store.js
- frontend/src/store/store.test.js
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/src/views/Pages/UserProfile/UserCard.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_Language.vue
- frontend/src/views/Pages/UserProfile/UserCard_Newsletter.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_Newsletter.vue
- frontend/src/views/Pages/UserProfileOverview.vue
User settings add Newsletter function
- UserCard_Newsletter.vue
- UserCard_Newsletter.spec.js
- fixes #531
> newsletter subscribe status change in user profile

- frontend/src/views/Pages/UserProfile/UserCard_Language.vue
> [WIP] UserProfil Language switch has an error & UserProfil Language switch don't show right language text

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/UserProfile/UserCard_Language.vue
The language switch in profile didn't show a success message, and didn't change the site language
- fixes #733
> 733 language switch toast success

- backend/src/graphql/resolvers/TransactionResolver.ts
- backend/src/graphql/resolvers/UserResolver.ts
- frontend/src/components/LanguageSwitch.spec.js
- frontend/src/components/LanguageSwitch.vue
- frontend/src/graphql/mutations.js
- frontend/src/graphql/queries.js
- frontend/src/views/Pages/AccountOverview.spec.js
- frontend/src/views/Pages/AccountOverview.vue
- frontend/src/views/Pages/Register.spec.js
- frontend/src/views/Pages/Register.vue
- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/ResetPassword.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserMail.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserMail.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.vue
- frontend/src/views/Pages/UserProfile/UserCard_Language.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_Language.vue
Makes the queries that alter data in the DB to mutations
- fixes #742
Fixes the bug that a user cannot change the language in the profile
> refactor: Queries to Mutations

- frontend/src/views/Pages/UserProfile/UserCard.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
- frontend/src/views/Pages/UserProfile/UserCard_Language.vue
- frontend/src/views/Pages/UserProfile/UserCard_Newsletter.vue
- frontend/src/views/Pages/UserProfileOverview.vue
round corners removed from profile settings page 
- fixes #850
- fixes #851
- fixes #859
> round corners removed from profile settings page

- backend/src/graphql/resolvers/BalanceResolver.ts
- backend/src/graphql/resolvers/GdtResolver.ts
On top of apollo get balance (#831) so better merge that before
Simply get email address from db and then call api call direct from gdt server, the community-server call is only a proxy to.
- fixes #821
> Apollo list gdt transactions

- frontend/src/components/Transaction.vue
- frontend/src/components/TransactionCollapse.vue
- bug fix: givenType 2,3,5,6 change to givenType 1
-  fix: <div class="col-6 ...">  CHANGE TO <b-col cols="6" class="...">
- relates #XXX
> bug fix givenType 2,3,5,6 change to givenType 1

- frontend/src/components/DecayInformation.vue
- frontend/src/components/Transaction.vue
- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
there was an error with <b-col col="6"> 
col= was replaced by cols=
> fix bug col to cols on <b-col>

- frontend/src/views/Pages/AccountOverview/GddTransactionList.spec.js
- frontend/test/testSetup.js
Set correct data type for balance in Gdd transaction list unit test
> fix: Warnings in Gdd Transaction List Spec

- frontend/src/components/LanguageSwitchSelect.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/ForgotPassword.spec.js
- frontend/src/views/Pages/ForgotPassword.vue
- frontend/src/views/Pages/Login.spec.js
- frontend/src/views/Pages/Login.vue
- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/ResetPassword.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_FormUsername.vue
- frontend/src/views/Pages/UserProfile/UserCard_Language.vue
- frontend/src/views/Pages/UserProfile/UserCard_Newsletter.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_Newsletter.vue
I have tidied up the language files to list everything that belongs to the settings. 
- fixes #902  
- fixes #898
> Cleaned up locales for settings and adjusted texts in files

- frontend/.env.dist
- frontend/src/config/index.js
Only the GraphQL-Endpoint is required in the frontend. The Login & Community endpoints are no longer required.
- None
> Remove api endpoints from frontend config

- .github/workflows/test.yml
- frontend/src/views/Pages/UserProfile/UserCard_Language.spec.js
- frontend/src/views/Pages/UserProfile/UserCard_Language.vue
- frontend/src/views/Pages/UserProfile/UserCard_Newsletter.spec.js
* Test all the functionality of the component to change the language in the user profile
* line coverage of newsletter component to 100%
* coverage of unit tests frontend to 69%
> feat: Test Change Language in User Profile

- backend/src/typeorm/getDBVersion.ts
This part affects only the migration query to simplify it.
- None
> fix migrations to use only the entity model

- backend/src/graphql/resolvers/BalanceResolver.ts
- backend/src/graphql/resolvers/TransactionResolver.ts
- backend/src/typeorm/repository/Balance.ts
- docker-compose.override.yml
- frontend/src/graphql/queries.js
Fixed several bugs introduced in the latest changes of Dario and I.
- Order bug in frontend query
- gdtSum must be a number
- run database migrations in test mode
- missing enum comparison
- fixed a broken query failing if user was not found
- minor refactors
- None
> Bug fixes recent changes

- .github/workflows/test.yml
- database/src/prepare.ts
This should fix the test database workflow creation without creating two databases by default
- None
> Community test database fix

- frontend/vue.config.js
Webpack is a blabber mouth. This adds a wool blanket.
- fixes #933
> silence webpack, it was very noisy

- frontend/src/routes/guards.test.js
> feat: Improve Test of Navigation Guard of Vue Router

- frontend/src/components/SidebarPlugin/SideBar.vue
> fix publisherId config

- frontend/src/components/DecayInformation.vue
> error rounding in transactions list fixed

- frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
Use transaction ID with decay prefix as identifier for the collapse element.
- fixes #982
> fix: Use TransactionId as Collapse Identifier

- frontend/src/graphql/mutations.js
Registration without publisherId triggered an error.
- None
> Change the publisherId to nullable.

- frontend/src/locales/de.json
> fix language registriert

- .github/ISSUE_TEMPLATE/release.md
adjusted release issue template to use new icon see: https://github.com/ulfgebhardt/issue-templates/commit/1f3f9cc4d7cdf2dd47ac1b35fa1ad9b62a84c579
This is to make it match our current Zenhub Icon
- None
> release_issue_template

- frontend/package.json
- frontend/vue.config.js
- frontend/yarn.lock
allow bundle analysis:
- generate webpack stats
- have a `analyse-bundle` command to start visualization
- releates #741
> analyse_bundle

- backend/src/graphql/resolver/TransactionResolver.ts
fixes the rounding of the decay.
- fixes #997
> fix: Decay Rounded to Ceil

- frontend/src/views/Pages/CheckEmail.vue
checkEmail.vue page text is displayed correctly now
- fixes #1050
> checkEmail.vue page text is displayed correctly now

- frontend/src/locales/de.json
Spelling error fixed 
- fixes #1047
> Spelling error fixed 'Berechnungsformel'

- .vscode/extensions.json
suggest some extensions
- None
> vscode_suggest_extensions

- login_server/src/cpp/controller/User.cpp
- login_server/src/cpsp/CheckTransaction.cpsp
- fix error in user-search (came with publisher_id adding)
- fix broken cancel button in checkTransactions 
- move cancel button after skip button in checkTransactions
> Login hotfixes 1.5.1

- README.md
I did a clean install and documented my steps and findings.
updated readme:
- accurate software requirements
- arch linux install instructions
- service description
- troubleshooting
- relates #1062 
- relates #1063 
- relates #1064
> fresh_install_instructions

- backend/src/graphql/resolver/UserResolver.ts
- database/entity/0003-login_server_tables/LoginElopageBuys.ts
- database/entity/LoginElopageBuys.ts
- database/entity/index.ts
Implements the `hasElopage` call which has been implemented on the `login_server` before.
- none
> login_call_hasElopage

- backend/src/graphql/resolver/UserResolver.ts
"implemented" logout call
- fixes #834
> login_call_logout

- .github/workflows/test.yml
- frontend/src/plugins/globalComponents.test.js
- frontend/src/views/Pages/SendOverview/GddSend/QrCode.spec.js
- frontend/src/views/Pages/SendOverview/GddSend/QrCode.vue
> feat: Raise Test Coverage Frontend

- backend/src/graphql/directive/isAuthorized.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/src/jwt/decode.ts
- backend/src/jwt/encode.ts
Withdraw sessionId from the jwt logic.
- relates #1095 
- relates #838
> Apollo jwt withdraw session

- database/entity/ServerUser.ts
Add entity `ServerUser` to our db model.
> feat: Add Server Users Entity

- .github/workflows/test.yml
- admin/src/main.js
> fix_admin_token_renewal

- frontend/src/components/Inputs/InputPassword.vue
register tabindex skips the button to view the password 
- fixes #1009
> register add tabindex-1 on password show

- backend/src/graphql/resolver/AdminResolver.ts
- backend/src/typeorm/repository/LoginPendingTasksAdmin.ts
renamed pendingCreations into loginPendingTasksAdmin as to our naming conventions
- None
> naming_conventions_pending_tasks

- .github/workflows/test.yml
- frontend/src/plugins/globalDirectives.js
- frontend/src/plugins/globalDirectives.test.js
- frontend/src/views/Layout/DashboardLayout_gdd.spec.js
- frontend/src/views/Pages/SendOverview.vue
Add some more tests to the resent changes and remove unused code.
> feat: Frontend Refactor and Tests

- backend/src/graphql/resolver/UserResolver.ts
fixed optIn Code generation - a new Code is now generated when the 10 min delay is expired
(this fix is for @Elweyn who is currently testing this feature - be aware that its not tested)
- None
> fix_optin_code_regeneration

- backend/src/graphql/arg/CreateUserArgs.ts
- backend/src/webhook/elopage.ts
> Withdrew password argument of createUser.

- admin/src/components/UserTable.vue
Wenn ich zwischen den pending creations wechsel um die daten zu editieren .. dann werden die daten jetzt sauber im formular gewechselt und angepasst. 
- fixes #1235
> change creationdatas if change pending creation

- admin/src/pages/UserSearch.spec.js
- admin/src/pages/UserSearch.vue
es wird gefiltert das alle  nutzer unregistrierten emails angezeigt werden 
- fixes #1231 
- Issues https://github.com/gradido/gradido/issues/1262
> reverse filter for unregistered emails

- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/ResetPassword.vue
zwischen zwei texten wechseln. 
- passwort zurücksetzen ändern  text 
- passwort das erste mal anlegen nach registrierung
- fixes #1240 
- fixes #1225 
Test müssten angepast werden
> 1240 account not activated needs a button to login page

- backend/src/graphql/resolver/TransactionResolver.ts
The user had another value in the gdt overview as in the list of gdts.
- fixes #1267
> Wallet shows the wrong gdt sum (gdtSum * 100)

- backend/src/graphql/resolver/AdminResolver.ts
- backend/src/graphql/resolver/UserResolver.ts
> fix: Change Password in User Profile

- database/src/factories/login-user.factory.ts
- database/src/index.ts
- database/src/interface/UserContext.ts
- database/src/interface/UserInterface.ts
- database/src/seeds/users/bibi-bloxberg.ts
- database/src/seeds/users/bob-baumeister.ts
- database/src/seeds/users/garrick-ollivander.seed.ts
- database/src/seeds/users/garrick-ollivander.ts
- database/src/seeds/users/peter-lustig.ts
- database/src/seeds/users/raeuber-hotzenplotz.ts
Garrick Ollivander has not confirmed his email yet.
- fixes #1258
- fixes #1238
> feat: Seed Garrick Ollivander

- admin/src/components/CreationTransactionListFormular.spec.js
- admin/src/components/CreationTransactionListFormular.vue
- admin/src/components/UserTable.spec.js
- backend/src/typeorm/repository/UserTransaction.ts
> fix: Admin Creation List

- frontend/src/locales/de.json
- frontend/src/locales/en.json
update for the langauge strings I got from Bernd
- None
> language_updates_bernd

- frontend/src/views/Pages/AccountOverview.vue
The layout had a horrizontal scrollbar in every screen size. 
This PR fixes the layout so we don't have any horrizontal scrollbar anymore.
- fixes #1248
> Withdrew horrizontal scrollbar

- frontend/src/components/Menu/Navbar.vue
- frontend/src/components/Menu/Sidebar.vue
add icons in menu and navbarmenu
- fixes #1250
> add icons in menu and navbarmenu

- admin/src/components/NavBar.vue
- admin/src/locales/de.json
- admin/src/locales/en.json
rename Wallet to "My Account
- fixes #1307
> 1307 admin rename wallet to my account

- frontend/src/views/Pages/AccountOverview.vue
Style geändert, border style inset, border radius 
- fixes #1249
> 1249 gdd gdt values look displaced or cut off

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/Register.vue
Der Satz “ Dies ist für die Registrierung nicht nötig” ist entfernt  
- fixes #1299
> 1299 remove text from register publisher

- admin/src/components/NavBar.vue
change Admin Gradido-Logo font color to white
- fixes #1306
> change Admin Gradido-Logo font color to white

- frontend/src/views/Pages/Register.spec.js
- frontend/src/views/Pages/Register.vue
Wenn nicht aktiv > hell
Wenn aktive > blau
- fixes #1300
nicht aktiv
aktiv
> 1300 gray out register button further when disabled

- backend/src/graphql/directive/isAuthorized.ts
fix broken login with existing token in local store
- fixes #1305
> fix_rejected_login

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/views/Pages/ResetPassword.spec.js
- frontend/src/views/Pages/ResetPassword.vue
Es wird beim request geprüft welche url verwendet wird. und die jeweilige url an thx aufgerufen .. 
- fixes #1303 
wenn checkMail passwort eingabe success
wenn passwort ändern success
> 1303 thanks page after set password

- frontend/src/components/Menu/Sidebar.vue
fette schrift auf menu , der seite die active ist 
https://user-images.githubusercontent.com/1324583/150812378-92b0c1e7-36b1-47ed-980e-c5a302e2dbc7.mp4
> bold text if acive page

- backend/src/graphql/resolver/TransactionResolver.ts
division / 100 from GDT TransactionResolver removed
- fixes #1338
> remove division / 100 for GDT

- database/migrations/0006-login_users_collation.ts
- deployment/bare_metal/install.sh
- deployment/bare_metal/setup.md
Changes we did for the production setup
- None
> production_deployment

- admin/src/locales/de.json
rechtschreibfehler behoben
Zeile 42 : "question": "Willst du diese vorgespeicherte Schöpfung wirklich vollziehen und endgültig speichern?",
- fixes #1353
> Rechtschreibfehler behoben, entgültig zu endgültig

- frontend/package.json
- frontend/src/main.js
- frontend/yarn.lock
upgrade vue version from ^2.6.11 to 2.6.12
- fixes #1380
> upgrade vue version from ^2.6.11 to 2.6.12

- .github/workflows/test.yml
- admin/src/components/UserTable.vue
- admin/src/pages/Creation.spec.js
Test the Creation page by clicking o the elements.
- relates #1155
> feat: Improved Tests for Mass Creation

- .github/workflows/test.yml
- admin/src/pages/UserSearch.spec.js
First steps to test the row details toggling in user search
- fixes #1155
> feat: Test Table Row Details Toggling

- frontend/src/views/Layout/ContentFooter.vue
- frontend/src/views/Pages/UserProfile/UserCard.vue
1. Style in profil settings page, header
2. style refactor for footer
> Profil settings and footer refactor

- backend/package.json
- backend/src/server/plugins.ts
- backend/yarn.lock
Fix: Do not log password or token to the console
- fixes #1475 
- relates https://github.com/shellscape/apollo-log/issues/17
> Fix: Do not log password or token to the console

- admin/src/components/ContentFooter.vue
show current version in footer
dieses PR ist auch im PR #1515 beinhaltet
- fixes #1461
> feature: show current version in admin footer

- admin/src/components/NotFoundPage.spec.js
- admin/src/components/NotFoundPage.vue
- admin/src/locales/de.json
- admin/src/locales/en.json
- frontend/src/views/NotFoundPage.spec.js
- frontend/src/views/NotFoundPage.vue
das PR #1514  ist teil dieses PRs ... sorry 
dieses PR hat auf die PageNotFound Seiten im Frontend der Wallet  und im Adminbereich ein go -1 gelegt. 
es wurde unter dem 404 Bild ein Button mit entsprechnder click funktion gelegt. aber auch das bild selber hat die selbe click version. 
sorry: leider ist das PR vorher #1514 mit drin .. da ich vergessen habe ein checkout zu machen. 
da das vorherige aber nur eine seite btrifft .. hoffe ich das dies nicht so problematisch ist. 
es betrifft die version im footer im adminbereich
- fixes #1466 , #1461
> 404 page needs back to login button

- backend/src/graphql/resolver/AdminResolver.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/src/typeorm/repository/User.ts
This implements the backend part of the soft-delete feature. By default users are not found which are deleted - in specific cases like `register`, `login`, `send`  and several admin queries, we have to make sure we also include the deleted accounts and give specific error messages
- fixes #1504
- requires #1516
> feature: Soft-Delete for users (backend)

- backend/src/graphql/resolver/UserResolver.ts
- backend/src/typeorm/repository/User.ts
some small refactors for the user resolver:
- stop using repositories where its not needed
- removed unused function
- None
> Refactor: User resolver

- backend/package.json
- backend/src/graphql/resolver/AdminResolver.ts
- backend/yarn.lock
Use only one query to get the amount for open users.
- relates #1456
> refactor: Get Open Creations by One Query

- backend/package.json
Correct path of index.js in production
- None
> Fix: Correct path of index.js in production

- backend/src/graphql/resolver/AdminResolver.ts
> fix: Return Empty Array When No Pending Creations Are Present

- admin/package.json
- backend/package.json
- backend/src/graphql/resolver/TransactionResolver.ts
- database/migrations/0001-init_db.ts
- database/migrations/0002-add_settings.ts
- database/migrations/0003-login_server_tables.ts
- database/migrations/0004-login_server_data.ts
- database/migrations/0005-admin_tables.ts
- database/migrations/0006-login_users_collation.ts
- database/migrations/0007-login_pending_tasks_delete.ts
- database/migrations/0008-state_users_plug_holes.ts
- database/migrations/0009-login_users_plug_holes.ts
- database/migrations/0010-login_users_state_users_sync.ts
- database/migrations/0011-login_user_backups_plug_holes.ts
- database/migrations/0012-login_user_backups_unify_wordlist.ts
- database/migrations/0013-drop_unused_tables.ts
- database/migrations/0014-drop_unused_tables_with_data.ts
- database/migrations/0015-admin_pending_creations.ts
- database/migrations/0016-transaction_signatures.ts
- database/migrations/0017-combine_user_tables.ts
- database/migrations/0018-combine_login_user_backups_and_user_table.ts
- database/migrations/0019-replace_login_user_id_with_state_user_id.ts
- database/migrations/0020-rename_and_clean_state_users.ts
- database/migrations/0021-elopagebuys_fields_nullable.ts
- database/migrations/0022-delete_decay_start_block.ts
- database/migrations/0023-users_disabled_soft_delete.ts
- database/migrations/0024-combine_transaction_tables.ts
- database/package.json
- frontend/package.json
This PR disallows lint warnings.
It also fixes all the lint warnings which have been around,
- None
> Feature: Make lint warnings unwanted

- admin/src/locales/de.json
- admin/src/locales/en.json
> fix: Wrong Key Name for Recover User

- backend/src/graphql/resolver/AdminResolver.ts
Checks that the user is not deleted when confirming a creation.
- fixes #1509
> fix: No Creations for Deleted Users

- database/src/index.ts
- database/src/seeds/users/stephen-hawking.seed.ts
- database/src/seeds/users/stephen-hawking.ts
Have a deleted user in seeded data. The deleted user can not login. When admin recovers the user, the user can login again.
- fixes #1503
> feat: Seed Deleted User

- backend/src/graphql/model/TransactionList.ts
Define balance type as Decimal not number
- None
> Fix: Balance type

- backend/src/graphql/resolver/TransactionResolver.ts
- database/entity/0029-clean_transaction_table/Transaction.ts
allow sending to user without transactions
- None
> Fix: Allow sending to user without transactions

- backend/src/graphql/resolver/UserResolver.ts
validate validity of user password when updating it via updateUserInfos
- fixes #588
> Fix: Validate password on UpdateUserInfos

- frontend/src/App.vue
- frontend/src/components/GddTransactionList.vue
- frontend/src/components/Transactions/TransactionCreation.vue
- frontend/src/components/Transactions/TransactionDecay.vue
- frontend/src/components/Transactions/TransactionReceive.vue
- frontend/src/components/Transactions/TransactionSend.vue
add style in App.vue, set class .pointer on transaction-list-item
- fixes #1581
- fixes #1582
> add style in App.vue, set class .pointer on transaction-list-item

- backend/src/config/index.ts
- backend/src/graphql/model/TransactionLink.ts
- backend/src/graphql/resolver/UserResolver.test.ts
- database/entity/0030-transaction_link/TransactionLink.ts
- database/entity/TransactionLink.ts
- database/entity/index.ts
- database/migrations/0030-transaction_link.ts
Model and entity for transaction links.
- relates #1551
> feat: Model Transaction Link

- backend/package.json
- backend/src/index.ts
- deployment/bare_metal/logrotate/gradido.conf.template
- deployment/bare_metal/nginx/update-page/updating.html.template
- deployment/bare_metal/start.sh
- Only rotate logfile, not already rotated files.
- dates in logfile names
- save update log
- fixed bug with module aliases when running the compiled files
- fixes #1452 
- fixes #1453 
- fixes #1403
> Fix: Logrotate & Log Dates & Save Update Log & Correct tag Checkout

- .github/workflows/test.yml
- backend/src/graphql/directive/isAuthorized.ts
- backend/src/graphql/resolver/UserResolver.test.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/test/helpers.ts
Test the logout query in user resolver. Improve helpers to handle context object to have an authenticated user.
- None
> feat: Test Logout in User Resolver

- backend/src/graphql/model/TransactionList.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/typeorm/repository/TransactionLink.ts
- frontend/src/components/DecayInformations/CollapseLinksList.vue
- frontend/src/components/DecayInformations/DecayInformation-Short.vue
- frontend/src/components/GddTransactionList.vue
- frontend/src/components/TransactionRows/LinkCountRow.vue
- frontend/src/components/Transactions/TransactionCreation.vue
- frontend/src/components/Transactions/TransactionDecay.vue
- frontend/src/components/Transactions/TransactionLink.vue
- frontend/src/components/Transactions/TransactionReceive.vue
- frontend/src/components/Transactions/TransactionSend.vue
- frontend/src/graphql/queries.js
- frontend/src/layouts/DashboardLayout_gdd.spec.js
- frontend/src/layouts/DashboardLayout_gdd.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/pages/Overview.vue
- frontend/src/pages/Transactions.vue
ich habe neu angelegt:
- frontend/src/components/Transactions/TransactionLink.vue
- frontend/src/components/TransactionRows/LinkCountRow.vue
- frontend/src/components/DecayInformations/CollapseLinksList.vue
https://user-images.githubusercontent.com/1324583/158010916-c31ebad6-e60f-404d-b9f0-72b8df838849.mp4
Todo: wir benötigen die anzahl aller aktieven Links im transaktionstype TRANSACTION_LINK
- fixes https://github.com/gradido/gradido/issues/1554
> 1554 frontend transaction link summary 

- frontend/src/components/GddSend/TransactionForm.spec.js
- frontend/src/components/GddSend/TransactionForm.vue
- frontend/src/components/GddSend/TransactionResultSendError.vue
- frontend/src/layouts/DashboardLayout_gdd.spec.js
- frontend/src/layouts/DashboardLayout_gdd.vue
- frontend/src/pages/Send.spec.js
- frontend/src/pages/Send.vue
die balance wird upgedated +  ~ decay für 14 tage
- fixes #1636 
https://user-images.githubusercontent.com/1324583/159435069-7c06aba9-09b2-4d89-8b41-70748835c365.mp4
> update-balance if link succesfully generated

- admin/src/pages/UserSearch.vue
adminarea:  fetchPolicy on searchUser deleted User
deleted users are reloaded on click  
- fixes #1649
> adminarea:  fetchPolicy on searchUser deleted User

- frontend/src/components/TransactionRows/AmountAndNameRow.vue
- frontend/src/components/TransactionRows/TypeIcon.vue
- frontend/src/components/Transactions/TransactionReceive.vue
- frontend/src/components/Transactions/TransactionSend.vue
- frontend/src/graphql/queries.js
- frontend/src/locales/de.json
- frontend/src/locales/en.json
set link icon if transactionLinkId not null 
- fixes #1594
> 1594 show transaction was created by link

- frontend/src/components/GddSend/TransactionForm.vue
- frontend/src/pages/Send.vue
reset send formular if send link confirm go back to transacton send formular
- fixes #1684
> 1684 when generating a link form does not reset

- frontend/src/pages/Send.spec.js
- frontend/src/pages/Send.vue
the backend returns an array of errors, we display the first
- None
> Fix: Frontend show proper error message on failed send

- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/util/validate.ts
This fix makes sure we can send all our GDD via link.
- None
> Fix: Allow sending of more then half of my wealth via link

- backend/src/graphql/resolver/BalanceResolver.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/util/virtualTransactions.ts
This PR makes sure we calculate the decay on the last booked value NOT including the link values.
- None
> Fix: Correct calculation of decay

- frontend/src/components/DecayInformations/DecayInformation-Long.vue
icon is larger and position correctly
- fixes #1712
> icon droplet-halflarger and correctly positioned

- frontend/src/components/GddSend/TransactionConfirmationLink.vue
fix-disbled-button-if-totalBalance
- fixes #1703
> fix-disbled-button-if-totalBalance

- deployment/bare_metal/restore.sh
load database .env instead of backend .env
- None
> Fix: restore script load correct .env

- frontend/src/components/DecayInformations/DecayInformation-Decay.vue
- frontend/src/components/DecayInformations/DecayInformation-Long.vue
larger icon and deacy information if center
> Fix: larger icon and decay information if center

- frontend/src/locales/de.json
- frontend/src/locales/en.json
text for toast expand link copied
- fixes #1725
> text for toast expand link copied

- frontend/src/components/GddSend/TransactionForm.spec.js
- frontend/src/components/GddSend/TransactionForm.vue
transaction type remains when jumping from the verification back to the transaction form
- fixes #1723 
https://user-images.githubusercontent.com/1324583/161419778-24715589-0b98-4582-a35a-2cdda39a1893.mp4
> transaction type remains when jumping from the verification back

- frontend/src/components/DecayInformations/CollapseLinksList.spec.js
- frontend/src/components/TransactionLinks/TransactionLink.spec.js
- frontend/src/components/TransactionRows/DateRow.vue
- frontend/src/components/Transactions/TransactionLinkSummary.spec.js
- frontend/src/locales/de.json
- frontend/src/locales/en.json
the date for the validity display was changed exact date with time 
- fixes #1757
> better date format for reddem valid date

- admin/package.json
- admin/yarn.lock
- backend/package.json
- backend/yarn.lock
- database/package.json
- database/yarn.lock
- frontend/package.json
- frontend/yarn.lock
fixes yarn for windows in backend, admin, frontend, database packages.json by adding cross-env
> Fix: cross-env for windows

- .github/workflows/test.yml
- backend/src/graphql/resolver/UserResolver.test.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/src/seeds/graphql/mutations.ts
- backend/src/seeds/graphql/queries.ts
Adds more tests to the user resolver.
- relates #955
> feat: More User Resolver Tests

- frontend/src/components/ClipboardCopy.vue
- frontend/src/components/TransactionLinks/TransactionLink.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
wenn ältere Geräte keine **_navigator.clipboard_** Funktion haben und eine Fehlermeldung kommt
das der link nicht kopiert werden kann , habe ich folgende Lösung. 
- fixes #1837 
https://user-images.githubusercontent.com/1324583/165265762-ca18c3c7-6c54-4274-8157-8657b6171d81.mp4
https://user-images.githubusercontent.com/1324583/165265770-71326c3d-b499-47c2-8800-235094a686db.mp4
> error message by no navigator.clipbord function 

- deployment/bare_metal/start.sh
> devops: Disable DB Reset on Stage 1

- backend/src/seeds/index.ts
> fix: Deprecated Warning from Faker on Seeding

- frontend/src/components/Transactions/TransactionLinkSummary.spec.js
- frontend/src/components/Transactions/TransactionLinkSummary.vue
> fix: Loading Transaction Links after Reopening Link List

- deployment/bare_metal/setup.md
Add information about domain name and github secret to deployment documentation
- None
> docu: Update Deployment Documentation

- database/migrations/0026-combine_transaction_tables2.ts
- database/migrations/0027-clean_transaction_table.ts
- database/migrations/0029-clean_transaction_table.ts
- database/migrations/0035-admin_pending_creations_decimal.ts
- deployment/bare_metal/start.sh
Fix up migrations to have them running on servers.
- None
> fix: Up and Down Migrations for Older SQL Versions

- backend/src/graphql/resolver/BalanceResolver.ts
> fix: Count Deprecated Links as Well

- backend/src/typeorm/connection.ts
> fix: Database Connection Charset to utf8mb4_unicode_ci

- frontend/src/components/Auth/AuthFooter.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/pages/Login.vue
- Anmeldung speichern wurde entfernt
- text wurde zu for each other geändert
- farbe der icons wurde geändert 
- fixes #1952
> 1952 change footer icons color an remove save login

- frontend/src/pages/ForgotPassword.spec.js
- frontend/src/pages/ForgotPassword.vue
at the password forgotten and the page where i enter the email . i have removed the grey box and the link 'back'.
- fixes #1951
> 1951 remove back link and remove gray box

- frontend/src/assets/scss/gradido-template.scss
- frontend/src/components/Auth/AuthMobileStart.vue
- frontend/src/layouts/AuthLayout.vue
- frontend/src/pages/TransactionLink.vue
when redeeming a redeem link, the mobile start cover sheet is hidden in the mobile version
- fixes #1956 
https://user-images.githubusercontent.com/1324583/171336847-20da98cf-2dbf-4de3-9f18-cc052c6168b5.mp4
> fixed redeem link is mobile start false

- frontend/src/pages/Register.vue
submit button positioned on the left side of the register page. 
this way there is no more shift in dynamic changes and it is symmetrical to the login. 
- fixes #1963 
https://user-images.githubusercontent.com/1324583/171566437-04ee7f58-29d8-4373-98d3-bca53e47f93c.mp4
> refactor register button position

- frontend/src/components/Auth/AuthNavbar.vue
navbar "about gradido" link to english gradido site
> locales link german, english navbar

- admin/yarn.lock
- frontend/yarn.lock
dito
- there is one, which I cannot fins
> devops: Update Browser List for Unit Tests as Recomended

- frontend/src/components/Auth/AuthMobileStart.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
"Die neue Währung" / "The new Currency " deleted
- fixes #2036
> change text from page

- backend/src/graphql/model/User.ts
- backend/src/graphql/resolver/UserResolver.ts
> feat: Login Returns Open Creations for User

- frontend/src/components/Contributions/ContributionForm.spec.js
- frontend/src/components/Contributions/ContributionForm.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/pages/Community.spec.js
As user I would like to have the same error messages as on the send transaction form.
- fixes #2081
> [Feat] Replace logic to validation-provider.

- backend/src/graphql/resolver/ContributionResolver.ts
Fixes the `Cannot read properties of null (reading 'id')` error for the list all contributions query.
- None
> fix: Use Inner Join for Contribution and User

- frontend/src/components/ClipboardCopy.vue
- frontend/src/components/GddSend/TransactionResultLink.vue
- frontend/src/components/TransactionLinks/TransactionLink.vue
- frontend/src/graphql/mutations.js
- frontend/src/mixins/copyLinks.js
- frontend/src/pages/Send.spec.js
- frontend/src/pages/Send.vue
A follow up to #2099 - add the validation date info to the copied link and text.
- fixes #2077
> Add validation date info to copied text after transaction link creation

- frontend/src/components/Menu/Navbar.spec.js
- frontend/src/components/Menu/Navbar.vue
- frontend/src/components/Menu/Sidebar.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
In the mobile devices we could not see the community item & Remove block that insert an exclamation point for members area.
- None
> Fix navbar community item

- frontend/src/components/Contributions/ContributionForm.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
I have removed the required from.memo from the validation so that no message appears at the memo textarea after the reset. 
- fixes #2113 
https://user-images.githubusercontent.com/1324583/183091754-140ccbcb-adb1-42b4-b977-5245d11bb88a.mp4
> remove required from form.memo

- frontend/src/components/Contributions/ContributionForm.vue
comma and dot in the number are removed
- fixes #2112 
https://user-images.githubusercontent.com/1324583/183102711-4f96351f-efeb-46de-bc94-b080172f2765.mp4
> add formatter on input amount replace point and comma

- backend/src/config/index.ts
- backend/src/graphql/enum/ContributionStatus.ts
- backend/src/graphql/enum/ContributionType.ts
- backend/src/graphql/resolver/AdminResolver.ts
- backend/src/graphql/resolver/ContributionResolver.ts
- backend/src/graphql/resolver/TransactionLinkResolver.ts
- database/entity/0045-add_denied_type_and_status_to_contributions/Contribution.ts
- database/entity/Contribution.ts
- database/migrations/0045-add_denied_type_and_status_to_contributions.ts
Add columns contribution type, contribution status, denied at and denied by to contributions table. Add enumerators for contribution type and contribution status. Set type and status accordingly.
- fixes #2129
> feat: Migrate Contributions Table

- frontend/src/pages/InfoStatistic.vue
Sum up booked decay and not yet booked decay.
- None
> fix: 🍰 Decay Calculation In Community Statistics

- frontend/.eslintrc.js
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/pages/InfoStatistic.spec.js
- frontend/src/pages/InfoStatistic.vue
As it takes far to long to generate the statistics, for now it is no longer shown in the wallet.
Locales are only checked for English and German
- None
> fix: Remove Statistics from Wallet

- backend/src/graphql/resolver/StatisticsResolver.ts
Reduce the time of the db Call to 2 seconds.
- None
> refactor: Improve Statistics Query

- admin/src/components/ContributionMessages/ContributionMessagesFormular.vue
- admin/src/components/ContributionMessages/slots/IsModerator.vue
- admin/src/components/ContributionMessages/slots/IsNotModerator.vue
- frontend/src/components/ContributionMessages/ContributionMessagesList.vue
- frontend/src/components/ContributionMessages/slots/IsModerator.vue
- frontend/src/components/ContributionMessages/slots/IsNotModerator.vue
text in contribution messages smaller
- fixes #2183
> text in messages smaller

- frontend/src/components/Contributions/ContributionListItem.vue
the button for the messages when a contribution is CONFIRMED is displayed again.
- fixes #2184
> messages show if Confirmed

- admin/src/components/ContributionMessages/ContributionMessagesFormular.vue
- frontend/src/components/ContributionMessages/ContributionMessagesFormular.vue
no message can be sent if the textarea is empty. 
- fixes #2188
> if message empty else disabled button

- frontend/src/components/Contributions/ContributionList.vue
- frontend/src/components/Contributions/ContributionListItem.vue
- frontend/src/pages/Community.vue
the icons in the allContribution list are removed
> fix: 🍰 Show Not Icons In `allContribution` List

- docu/Concepts/TechnicalRequirements/BusinessEventProtocol.md
> 2219 feature rework eventprotocol

- e2e-tests/cypress/README.md
- e2e-tests/cypress/tests/cypress.config.ts
- e2e-tests/cypress/tests/cypress/e2e/User.Registration.feature
- e2e-tests/cypress/tests/cypress/e2e/models/LoginPage.ts
- e2e-tests/cypress/tests/cypress/e2e/models/ProfilePage.ts
- e2e-tests/cypress/tests/cypress/e2e/models/RegistrationPage.ts
- e2e-tests/cypress/tests/cypress/e2e/models/Toasts.ts
- e2e-tests/cypress/tests/cypress/support/step_definitions/common_steps.ts
- e2e-tests/cypress/tests/cypress/support/step_definitions/user_profile_change_password_steps.ts
- e2e-tests/cypress/tests/package.json
- frontend/src/components/Inputs/InputPasswordConfirmation.vue
Fix reliability issues and an error related to missing files
- fixes #2243
> chore: 🍰 Fix Cypress Tests Unreliability

- .github/workflows/test.yml
- backend/src/graphql/enum/ContributionCycleType.ts
- backend/src/graphql/resolver/TransactionLinkResolver.test.ts
- backend/src/graphql/resolver/TransactionLinkResolver.ts
- backend/src/seeds/graphql/mutations.ts
- backend/yarn.lock
Add the daily rule for contribution links
Update the browser list for the unit tests. Therefore the changes in yarn.lock
- fixes #2223
> feat: 🍰 Daily Rule For Contribution Links

- backend/src/graphql/resolver/TransactionLinkResolver.test.ts
- backend/src/graphql/resolver/TransactionLinkResolver.ts
There is a bet sql statement to validate the redeem of a daily contribution link. Fix it.
- None
> fix: 🍰 Daily Redeem Of Contribution Link

- backend/src/config/index.ts
- backend/src/mailer/sendEMail.test.ts
> Fix: correctly evaluate to EMAIL_TEST_MODE to false

- frontend/src/pages/Community.vue
navigate with pagenation is solved
- fixes #2278
> fix: Pagination Contributions jumps to wrong Page

- admin/src/components/ContributionMessages/LinkifyMessage.vue
- frontend/src/components/ContributionMessages/LinkifyMessage.vue
The links in contribution messages pointed to a wrong URL 
- None
> fix: Link in Contribution Messages

- admin/src/components/ContributionMessages/LinkifyMessage.vue
- frontend/src/components/ContributionMessages/LinkifyMessage.vue
Links in contribution messages have target _blank
- None
> fix: 🍰 Links In Contribution Messages Target Blank

- frontend/src/components/ContributionMessages/ContributionMessagesList.vue
add button for close contribution messages box
- fixes #2291
> 2291 add button for close contribution messages box

- frontend/src/components/Contributions/ContributionForm.spec.js
- frontend/src/components/Contributions/ContributionForm.vue
the last and current month is displayed cleanly again. 
- fixes #2315
> bug: 2315 Contribution Month and TEST FAIL in MASTER

- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/pages/InfoStatistic.vue
Contact email under own heading
- fixes #2292
> 2292 community information contact

- admin/src/components/ContentFooter.vue
- admin/src/components/ContributionLinkList.vue
the horizontal scrollbar in the admin area no longer exists. 
the contribution left table breaks if below 993px width.
- fixes #2295
> bug: 2295 remove horizontal scrollbar in admin overview

- backend/src/graphql/resolver/StatisticsResolver.ts
dito. Hopefully this fixes server stability
- None
> fix: Release Statistic Query Runner

- frontend/src/components/GddSend/TransactionConfirmationSend.vue
Negative sign is not shown anymore.
- fixes #2293
> fix(frontend): amount negative when sending GDD

- admin/src/components/ContributionLink/ContributionLink.spec.js
- admin/src/components/ContributionLink/ContributionLink.vue
- admin/src/components/ContributionLink/ContributionLinkForm.vue
- admin/src/locales/de.json
- admin/src/locales/en.json
better behaviour when editing
- fixes #2355
> fix(admin): edit contribution link does not take old values

- admin/src/components/ContributionLink/ContributionLink.vue
- admin/src/components/ContributionLink/ContributionLinkForm.vue
- admin/src/components/ContributionLink/ContributionLinkList.vue
show error fixed after new contribution link and edit, delete link collapse cloce
> fix(admin): load error fixed for contribution link

- admin/src/locales/de.json
> fix(admin): fix text in admin area to uppercase

- frontend/src/pages/InfoStatistic.vue
> fix(frontend): mailto link

- backend/src/mailer/sendAddedContributionMessageEmail.test.ts
- backend/src/mailer/sendContributionConfirmedEmail.test.ts
- backend/src/mailer/sendContributionRejectedEmail.test.ts
- backend/src/mailer/sendTransactionReceivedEmail.test.ts
- backend/src/mailer/text/contributionConfirmed.ts
- backend/src/mailer/text/contributionMessageReceived.ts
- backend/src/mailer/text/contributionRejected.ts
- backend/src/mailer/text/transactionLinkRedeemed.ts
- backend/src/mailer/text/transactionReceived.ts
Correct E-Mail texts according to https://docs.google.com/document/d/1TqHTBWyCLx_Jh3EpsB27li5eTJ4k3ys3XHhKOlYND08/edit#
- None
> fix(backend): corrected E-Mail texts

- backend/Dockerfile
Copy missing files for docker production build when building the docker container
- None
> fix(other): missing files for docker production build

- backend/src/graphql/resolver/TransactionResolver.test.ts
- backend/src/graphql/resolver/TransactionResolver.ts
> fix(backend): critical bug

- backend/src/graphql/resolver/AdminResolver.test.ts
- backend/src/graphql/resolver/AdminResolver.ts
soft delete / restore email contact when deleting / undeleting an user
- relates #2436
> fix(backend): delete / undelete email contact as well

- .github/workflows/test.yml
- backend/src/graphql/resolver/semaphore.test.ts
Create a lot of traffic on the transaction table at the same time, see that there are no errors.
- None
> feat(backend): test semaphore

- backend/src/graphql/resolver/util/creations.test.ts
- frontend/src/components/ContentFooter.spec.js
frontend: expect current(local) year to be visible in the footer.
backend: expect a leading zero in months < October
- None
> test(other): fix tests breaking with the new year

- backend/src/emails/sendEmailVariants.test.ts
- backend/src/locales/en.json
> fix(backend): fix email text

- frontend/src/components/Menu/Navbar.vue
- frontend/src/components/Template/RightSide/LastTransactions.vue
Avatar initials always has 2 letters
- fixes #2529
> fix(frontend): avatar initials always has 2 letters

- frontend/src/components/Menu/Navbar.vue
- frontend/src/layouts/DashboardLayout.vue
leaves are over the user symbol
- fixes #2513
> fix(frontend): leaves are over the user symbol

- frontend/src/pages/Transactions.vue
pagination for gdt work
- fixes #2478
> fix(frontend): pagination gdt 

- .github/workflows/test.yml
- increase backend coverage requirement to 78%
- contributes to #1870
> test(backend): increase backend coverage to 78%

- admin/yarn.lock
- backend/yarn.lock
- frontend/yarn.lock
> fix(other): update browser list

- frontend/src/components/GddSend/TransactionConfirmationLink.vue
- frontend/src/components/GddSend/TransactionConfirmationSend.vue
- frontend/src/components/GddSend/TransactionForm.spec.js
- frontend/src/components/GddSend/TransactionForm.vue
- frontend/src/components/GddSend/TransactionResultLink.vue
- frontend/src/components/GddSend/TransactionResultSendSuccess.vue
- frontend/src/pages/Send.vue
send gdd and send link gdd is running
- fixes #2531
> fix(frontend):  send gdd and send link gdd is running

- backend/src/graphql/resolver/BalanceResolver.ts
- backend/src/graphql/resolver/ContributionResolver.test.ts
- backend/src/graphql/resolver/ContributionResolver.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- calculate last transaction correctly (2 occasions)
- disallow double confirmation of contributions already confirmed
- None
> fix(backend): fix backend not confirmable

- frontend/src/components/Template/RightSide/LastTransactions.vue
> fix(frontend): initials without space

- backend/package.json
removed jest from dependencies - only present in dev dependencies now
- None
> fix(backend): remove jest from dependecies

- .vscode/extensions.json
- .vscode/settings.json
- Added more extension recommendations
- added gradido default connection for the recommended sql tool
- None
> feat(other): vscode extensions

- frontend/src/layouts/DashboardLayout.vue
> fix(frontend): tunneled email on right side last transactions

- frontend/src/components/Inputs/InputHour.vue
scoop step in quarter hour set
- fixes #2565
> refactor(frontend): creation step in quarter hour set

- frontend/src/components/Contributions/ContributionForm.vue
mobil divices datepicker add props dropleft for dropdown menu
- fixes #2567
> fix(frontend): mobil divices datepicker add props dropleft 

- frontend/src/locales/en.json
english locales - horas -> hours
- None
> fix(frontend): english locales - horas -> hours

- backend/src/graphql/resolver/ContributionResolver.test.ts
- backend/src/graphql/resolver/ContributionResolver.ts
> fix(backend): admin cannot delete confirmed contribution

- frontend/src/locales/de.json
- frontend/src/locales/en.json
> fix(frontend): submit contribution text

- frontend/src/App.vue
- frontend/src/components/Contributions/ContributionListItem.vue
- frontend/src/components/Menu/Navbar.vue
- frontend/src/layouts/DashboardLayout.vue
> refactor(frontend): remove vertical scrolling & small fixes

- .github/workflows/test.yml
- frontend/src/components/ClipboardCopy.vue
- frontend/src/components/DecayInformations/CollapseLinksList.spec.js
- frontend/src/components/GddSend/TransactionResultLink.vue
- frontend/src/components/TransactionLinks/TransactionLink.spec.js
- frontend/src/components/Transactions/TransactionLinkSummary.spec.js
- frontend/src/mixins/copyLinks.js
- frontend/src/pages/Send.spec.js
link, link + text and QR code are displayed one below the other. text is also displayed. that you can see what you are copying. 
- fixes #2560
> refactor(frontend): link send result style

- frontend/src/components/Contributions/ContributionForm.vue
change dropdown placement calender no-flip true
> fix(frontend): change dropdown placement calender no-flip true

- frontend/src/components/Contributions/ContributionForm.vue
reduce min value to 0.25 to be consistent
- None
> fix(frontend): fix min value for hours input

- frontend/src/pages/ForgotPassword.spec.js
> refactor(frontend): forgot password unit tests

- frontend/src/assets/News/news.json
- frontend/src/locales/fr.json
> refactor(frontend): equalize en with fr languages.

- frontend/test/testSetup.js
fix error handling to throw proper errors
- None
> fix(frontend): throw proper frontend warning errors

- admin/src/components/CreationTransactionList.vue
- admin/src/components/Tables/OpenCreationsTable.spec.js
- admin/src/components/TransactionLinkList.vue
- admin/src/pages/CreationConfirm.vue
add test-break class on all table fields memo
> refactor(admin): add text-break on all table memo fields

- .github/workflows/test.yml
- frontend/src/components/Contributions/ContributionListItem.vue
- frontend/src/components/Inputs/InputTextarea.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/pages/Community.vue
add word-break in contribution memo
> refactor(frontend): change contribution memo add word-break

- .github/workflows/lint_pr.yml
properly lint pr - prevent requirement to restart linting
- None
> fix(workflow): properly lint pr - prevent requirement to restart linting

- backend/src/graphql/resolver/util/creations.test.ts
Unit tests for creations did not work on 31st day. Fixed
- None
> fix(backend): unit tests creations for 31st day

- backend/src/emails/sendEmailTranslated.ts
use LogError
- contributes to #2487
> refactor(backend): use LogError on sendEMailTranslated

- backend/src/event/Event.ts
- backend/src/event/EventProtocolEmitter.ts
- backend/src/graphql/resolver/ContributionResolver.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/graphql/resolver/UserResolver.ts
- database/entity/0043-add_event_protocol_table/EventProtocol.ts
- database/entity/0050-add_messageId_to_event_protocol/EventProtocol.ts
Refactor event protocol - simplify things.
- contributes to #1870
> refactor(backend): event protocol

- frontend/src/pages/InfoStatistic.vue
> fix(frontend): community link

- frontend/src/components/Contributions/ContributionForm.spec.js
- frontend/src/components/Contributions/ContributionForm.vue
- frontend/src/pages/Community.vue
> fix(frontend): fix is last month for empty form date

- admin/src/pages/CreationConfirm.spec.js
- admin/src/pages/CreationConfirm.vue
> fix(admin): deny contribution button to left

- backend/src/emails/sendEmailVariants.test.ts
- backend/src/locales/de.json
- backend/src/locales/en.json
> fix(backend): emails – adjust namings of menus to new design

- database/migrations/0060-update_communities_table.ts
> fix(database): change downwards migration to delete entries with last_announced_at IS NULL

- admin/src/locales/en.json
english language for contributions in admin
- None
> fix(admin): english language for contributions in admin

- admin/src/pages/CreationConfirm.vue
> fix(admin): update openCreation in case of tab open.

- frontend/src/components/Menu/Sidebar.vue
Bitte vor dem Releasen UNBEDINGT das Icon mit dem $-Zeichen rausnehmen. Das habe ich in fehler und Vorschläge schon geschrieben.
- None
> refactor(frontend): change b-img to b-icon send

- frontend/src/components/Contributions/ContributionListItem.vue
> fix(frontend): admin question clickable

- backend/jest.config.js
- backend/src/apis/KlicktippController.ts
- based on #2883
- relates #2707
> refactor(backend): upgrade coverage to 85%

- frontend/package.json
- frontend/yarn.lock
> fix(frontend): update jest-canvas-mock version to resolve window mock problem in tests

- admin/.eslintignore
- admin/.gitignore
- admin/Dockerfile
- admin/package.json
- admin/run/server.js
- admin/vue.config.js
- deployment/bare_metal/nginx/sites-available/gradido.conf.ssl.template
- deployment/bare_metal/nginx/sites-available/gradido.conf.template
- deployment/bare_metal/old/build_frontend.sh
- deployment/bare_metal/start.sh
- frontend/.eslintignore
- frontend/.gitignore
- frontend/Dockerfile
- frontend/package.json
- frontend/run/server.js
- frontend/vue.config.js
- nginx/gradido.conf
- Rename all dist folder to build
- Delete build folders
- fixes #2937 
- fixes #2976
> refactor(other): delete build folders

- admin/src/store/store.js
- e2e-tests/cypress/support/e2e.ts
- frontend/src/store/store.js
> fix(frontend): between store problems

- backend/.eslintrc.js
- backend/src/auth/JWT.ts
- backend/src/config/index.ts
- backend/src/federation/client/GraphQLGetClient.ts
- backend/src/federation/validateCommunities.ts
- backend/src/graphql/directive/isAuthorized.ts
- backend/src/graphql/model/Balance.ts
- backend/src/graphql/model/Transaction.ts
- backend/src/graphql/resolver/BalanceResolver.ts
- backend/src/graphql/resolver/ContributionResolver.test.ts
- backend/src/graphql/resolver/ContributionResolver.ts
- backend/src/graphql/resolver/TransactionLinkResolver.test.ts
- backend/src/graphql/resolver/TransactionLinkResolver.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/src/graphql/resolver/util/findContributions.ts
- backend/src/graphql/resolver/util/transactionLinkList.ts
- backend/src/index.ts
- backend/src/seeds/index.ts
- backend/src/server/createServer.ts
- backend/src/server/plugins.ts
- backend/src/typeorm/DBVersion.ts
- backend/src/util/klicktipp.ts
- backend/src/util/utilities.ts
- backend/src/webhook/elopage.ts
- backend/test/helpers.ts
This implements typescript strict checks except `@typescript-eslint/no-unnecessary-condition` since this is incompatible with typeorm
- fixes #2964
> refactor(backend): eslint typescript strict

- backend/.eslintrc.js
- backend/package.json
- backend/src/graphql/resolver/TransactionLinkResolver.test.ts
- backend/src/graphql/resolver/util/creations.ts
- backend/src/seeds/index.ts
- backend/src/server/logger.ts
- backend/src/util/utilities.ts
- backend/src/webhook/elopage.ts
- backend/yarn.lock
This PR introduces the `eslint-security` plugin, which does code analysis to warn about potential security issues.
While the PR fixes one security issue, it it ignores the remaining 9 since its either not a security concern or its not an easy fix.
The EMail Regex is a potential security flaw we have in our code(could run for long and if utilized correctly it could lead to an ddos attack) - lacking of an immediate solution I decided to ignore this issue.
The benefit is that, when merged, developers will be warned about potential security flaws they introduce with their code.
- based on #2979
> refactor(backend): eslint security

- backend/.eslintignore
- backend/.eslintrc.js
- backend/package.json
- backend/src/apis/HttpRequest.ts
- backend/yarn.lock
This PR lints the eslint-comments and prevents duplicate or unnecessary ignores.
- based on #2980
> refactor(backend): eslint comments

- frontend/src/components/GddSend/TransactionConfirmationSend.vue
- frontend/src/components/GddSend/TransactionForm.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
> feat(frontend): add community to send form

- backend/package.json
Changes in PUG JSON and CSS files don't reload the backend so I added them to have a better filling while working
- None
> fix(backend): add extension pug json and css to nodemon.

- frontend/src/components/Menu/Navbar.vue
- frontend/src/pages/Login.spec.js
- frontend/src/pages/Login.vue
- frontend/src/store/store.js
- frontend/src/store/store.test.js
> feat(frontend): preserve email after login

- backend/src/graphql/resolver/TransactionResolver.ts
> refactor(backend): remove to do after creating issue

- database/migrations/0066-x-community-sendcoins-transactions_table.ts
Remove duplicate comments from database migration
- None
> refactor(database): remove duplicate comments

- dht-node/src/dht_node/index.ts
simplify newCommunityUuid. Reduce the amount of variables used and make it smaller code.
Its equivalent in function.
- None
> refactor(federation): simplify newCommunityUuid

- dht-node/src/dht_node/index.ts
Just removes an unused export(CommunityApi)
- None
> refactor(federation): remove export from CommunityApi

- backend/.eslintrc.js
- backend/@types/random-bigint/index.d.ts
- backend/src/graphql/resolver/UserResolver.ts
Removes the manual `require()` of `random-bigint` by defining its types
- None
> refactor(backend): random-bigint types

- .github/workflows/lint_pr.yml
This PR adds the ability to write `dht` as part of the PR title validation - e.g. `feat(dht): ...`
- None
> feat(workflow): dht as package for lint pr workflow

- admin/src/components/Tables/OpenCreationsTable.vue
> feat(admin): change deny contribution btn-warning color and background-color to #e1a908

- e2e-tests/.eslintignore
- e2e-tests/.eslintrc.js
- e2e-tests/cypress.config.ts
- e2e-tests/cypress/e2e/models/OverviewPage.ts
- e2e-tests/cypress/e2e/models/ResetPasswordPage.ts
- e2e-tests/cypress/e2e/models/SendPage.ts
- e2e-tests/cypress/e2e/models/UserEMailSite.ts
- e2e-tests/cypress/support/index.ts
- e2e-tests/cypress/support/step_definitions/common_steps.ts
- e2e-tests/cypress/support/step_definitions/email_steps.ts
- e2e-tests/cypress/support/step_definitions/send_coin_steps.ts
- e2e-tests/cypress/support/step_definitions/user_authentication_steps.ts
- e2e-tests/cypress/support/step_definitions/user_profile_change_password_steps.ts
- e2e-tests/cypress/support/step_definitions/user_registration_steps.ts
> fix(other): linting in e2e tests directory does not work

- admin/src/components/CreationTransactionList.spec.js
- admin/src/components/UserQuery.vue
- admin/src/graphql/adminListContributions.js
- admin/src/pages/CreationConfirm.spec.js
- admin/src/pages/CreationConfirm.vue
- admin/src/pages/UserSearch.spec.js
- admin/src/pages/UserSearch.vue
based on #3091 
I cannot find an issue.
Adds a test input field on the contribution page to search for users.
- None
> feat(admin): query users on contributions

- backend/yarn.lock
yarn lock updated after typeorm upgrade
- None
> fix(backend): yarn.lock after typeorm update

- backend/src/graphql/resolver/ContributionMessageResolver.test.ts
- backend/src/graphql/resolver/ContributionMessageResolver.ts
> fix(backend): moderator message don't send email to user

- frontend/src/graphql/queries.js
- fixes #3104 
- [ ] Check for email in verifyLogin (Can not work)
> fix(frontend): add alias to the verifyLogin GraphQL answer.

- frontend/src/assets/News/news.json
date from deploy changed to infotext
- fixes #3102
> refactor(frontend): date from deploy changed to infotext

- frontend/src/components/Inputs/InputUsername.vue
- frontend/src/components/UserSettings/UserName.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/pages/Settings.vue
refactor changes incorporated
- fixes #3105 
https://github.com/gradido/gradido/assets/1324583/1869bea4-8e1f-45a9-8d25-9c221c5012cd
> refactor(frontend):  refactor changes incorporated

- frontend/src/assets/News/news.json
> refactor(frontend): text juni to juli

- frontend/src/locales/de.json
fix spelling German "Speichern" capital letter
- fixes #3121
> fix(frontend): fix German "Speichern" to have capital letter

- frontend/src/components/UserSettings/UserName.spec.js
- frontend/src/components/UserSettings/UserName.vue
properly save username, do not allow to edit it again
- None
> fix(frontend): properly save username, do not allow to edit it again

- backend/src/graphql/resolver/ContributionMessageResolver.test.ts
- backend/src/graphql/resolver/ContributionMessageResolver.ts
- backend/src/graphql/resolver/ContributionResolver.test.ts
- backend/src/graphql/resolver/ContributionResolver.ts
moderation message are completely hidden from the user
- do not show "Please respond..."
- do not show moderator chat button
- fixes #3120 #3126
> fix(backend): moderation message are completely hidden from the user

- backend/src/graphql/resolver/semaphore.test.ts
Set both parallel mutation in a promise.all block and check if there is an error and a success.
- None
> fix(backend): semaphore parallel redeemTransactionLink test

- docker-compose.override.yml
> fix(other): add missing volume for dlt-connector dev docker

- backend/log4js-config.json
- dht-node/log4js-config.json
- dlt-connector/log4js-config.json
- federation/log4js-config.json
Enable compression of Logfiles.
- None
> perf(backend): enable logfile compression

- deployment/bare_metal/removeLogFiles.sh
> fix(backend): update logfiles clearance-script

- scripts/release.sh
> feat(dlt): add dlt-connector to release-script

- admin/src/locales/de.json
- admin/src/locales/en.json
- admin/src/pages/CreationConfirm.vue
> feat(admin): update hashtag ui

- backend/jest.config.js
- backend/src/config/index.ts
- backend/src/graphql/enum/PendingTransactionState.ts
- database/entity/0071-add-pending_transactions-table/PendingTransaction.ts
- database/entity/PendingTransaction.ts
- database/entity/index.ts
- database/migrations/0071-add-pending_transactions-table.ts
- dht-node/src/config/index.ts
- federation/src/config/index.ts
> feat(database): x-sendcoins-2: add pending transactions table for x-community-tx

- backend/src/graphql/arg/TransactionSendArgs.ts
- backend/src/graphql/resolver/CommunityResolver.test.ts
- backend/src/graphql/resolver/CommunityResolver.ts
- backend/src/graphql/resolver/TransactionResolver.test.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/graphql/resolver/semaphore.test.ts
- backend/src/seeds/graphql/mutations.ts
- backend/src/seeds/graphql/queries.ts
- e2e-tests/cypress/support/step_definitions/send_coin_steps.ts
- frontend/src/components/CommunitySwitch.vue
- frontend/src/components/GddSend/TransactionConfirmationSend.vue
- frontend/src/components/GddSend/TransactionForm.spec.js
- frontend/src/components/GddSend/TransactionForm.vue
- frontend/src/graphql/mutations.js
- frontend/src/graphql/queries.js
- frontend/src/pages/Send.spec.js
- frontend/src/pages/Send.vue
- add community switch component
- use it in send coins
- show the choosen target community in confirm transaction component
- add target community id to mutation call
- update backend mutation add target community id as parameter (currently not used)
- fixes #2948
> feat(frontend): add community switch to send coins

- frontend/src/components/CommunitySwitch.vue
> feat(frontend): make community switch looking similar to other inputs

- backend/src/graphql/resolver/CommunityResolver.test.ts
- backend/src/graphql/resolver/CommunityResolver.ts
> feat(backend): x-sendcoins: filter on authenticated communities for selection

- backend/src/graphql/resolver/CommunityResolver.ts
- backend/src/graphql/resolver/util/communities.ts
- frontend/src/components/GddSend/TransactionForm.spec.js
- frontend/src/components/GddSend/TransactionForm.vue
- frontend/src/graphql/queries.js
- frontend/src/pages/Send.vue
I haven't checked tests,
but I have tried it with uuid from db and it worked
with this solution always gradido id and community uuid are needed or none, using only gradido id leads to an error.
can be fixed if neccessary
> feat(frontend): tunnel community UUId to send

- backend/src/config/index.ts
- backend/src/graphql/resolver/EmailOptinCodes.test.ts
- backend/src/graphql/resolver/UserResolver.test.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/src/graphql/resolver/util/communities.ts
- backend/src/seeds/community/index.ts
- backend/src/seeds/factory/user.ts
- database/migrations/0074-insert_communityuuid in_existing_users.ts
- dht-node/src/config/index.ts
- federation/src/config/index.ts
> fix(backend): new local user without communitiyuuid

- backend/src/config/index.ts
- backend/src/graphql/resolver/ContributionResolver.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- database/migrations/0079-fill_linked_user_id_of_contributions.ts
- dht-node/src/config/index.ts
- federation/src/config/index.ts
Use linked_user_id field of transactions on contribution transactions to store user id of moderator which has confirmed the transaction
needed for dlt-connector
- None
> feat(backend): fill linked_user_id for creation transactions

- frontend/src/components/Contributions/ContributionListItem.vue
Use day, month and year for contribution overview in fronted instead of only month and year.
> feat(frontend): use day for contribution dates

- frontend/src/assets/News/news.json
- frontend/src/components/Overview/CommunityNews.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
update news text on Overview page on frontend
> feat(frontend): update news text

- deployment/hetzner_cloud/README.md
- add Videos to deployment readme
- update install.sh, branch is now needed always
- remove server suggestions because it is working with smallest server and can be easy rescaled
> feat(workflow): add videos to deployment readme

- backend/src/graphql/resolver/TransactionResolver.test.ts
- backend/src/graphql/resolver/UserResolver.test.ts
- backend/src/graphql/resolver/UserResolver.ts
> fix(backend): prevent updating alias backend-side

- frontend/src/assets/News/news.json
- frontend/src/components/Overview/CommunityNews.vue
- frontend/src/pages/Overview.spec.js
- update news 
- add new option with intern links
> feat(frontend): update news

- frontend/src/components/SessionLogoutTimeout.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- remove `automatically logged out` message
> feat(frontend): remove automatically logged out message

- frontend/src/pages/Send.spec.js
- frontend/src/pages/Send.vue
- make sure parameter are reset while redirect to clean send page after sending gdds
> fix(frontend): link forwarding after using send with url parameters

- admin/src/components/ContributionLink/ContributionLinkForm.spec.js
- admin/src/components/ContributionLink/ContributionLinkForm.vue
- admin/src/graphql/createContributionLink.js
- admin/src/graphql/updateContributionLink.js
> fix(admin): fix contribution link

- admin/components.d.ts
- admin/run/server.js
- admin/vite.config.js
> feat(admin): fix import in node server

- admin/vite.config.js
> fix(admin): vite config updates

- admin/components.d.ts
- admin/src/components/EditCreationFormular.vue
Rewrite component script part so it works properly with updated vue 3
> fix(admin):  EditCreationFormular.vue fix

- admin/src/components/CreationFormular.vue
> fix(frontend): show updated gdd amount

- admin/src/components/CreationFormular.vue
- admin/src/components/Tables/SearchUserTable.vue
> fix(admin): creation tab disappearing after creating creation

- frontend/.nvmrc
Made .nvmrc file inline with admin
> feat(frontend): bump node in .nvmrc

- frontend/package.json
- frontend/src/config/index.js
- frontend/vite.config.js
- frontend/yarn.lock
> fix(frontend): change way of using env variables

- frontend/package.json
- frontend/src/config/index.js
- frontend/src/layouts/DashboardLayout.vue
- frontend/src/main.js
- frontend/vite.config.js
- frontend/yarn.lock
> chore(frontend): main js cleanup

- frontend/src/layouts/DashboardLayout.vue
Reassigned logout handler to use proper method.
> fix(frontend): fix logout handler

- frontend/src/config/index.js
Bring back env variables after merge
> fix(frontend): fixed after merge

- frontend/src/components/CommunitySwitch.vue
Fix issue with community switch update
> fix(frontend): fix how community switch is handled

- frontend/src/components/UserSettings/UserNewsletter.vue
> fix(frontend): fix newsletter state reactivity

- frontend/src/components/Contributions/ContributionListItem.vue
- frontend/src/components/Transactions/TransactionLinkSummary.vue
- frontend/src/components/Transactions/TransactionSend.vue
> fix(frontend): fix dropdown in transaction send and link

- admin/src/components/EditCreationFormular.vue
Add proper variables for refetch query in edit creation form
> fix(admin): fix message update

- admin/src/pages/CreationConfirm.vue
- frontend/src/components/TransactionLinks/TransactionLink.vue
- frontend/src/components/Transactions/TransactionCreation.vue
Add style fixes raised during feedback, fixed number refreshed in badge in admin for open creations
> fix(frontend): style fixes, admin fix

- frontend/src/components/DecayInformations/DecayInformation-BeforeStartblock.vue
- frontend/src/components/DecayInformations/DecayInformation-Long.vue
- frontend/src/components/TransactionRows/MemoRow.vue
Add mapping for links and mails and swap them into clickable links.
> feat(frontend): links and emails in messages

- admin/src/components/Federation/CommunityVisualizeItem.vue
- admin/src/components/input/Coordinates.spec.js
- admin/src/components/input/Coordinates.vue
- admin/src/components/input/EditableGroup.vue
- admin/src/components/input/EditableGroupableLabel.spec.js
- admin/src/components/input/EditableGroupableLabel.vue
- docker-compose.yml
- frontend/src/assets/scss/gradido-template.scss
- frontend/src/components/DecayInformations/CollapseLinksList.vue
- frontend/src/components/GddSend/TransactionResultSendSuccess.vue
- frontend/src/components/Menu/Sidebar.vue
- frontend/src/components/MobileSidebar/MobileSidebar.vue
- frontend/src/components/SessionLogoutTimeout.vue
- frontend/src/components/SkeletonLoaderElement.vue
- frontend/src/components/UserSettings/UserNewsletter.vue
- frontend/src/components/skeleton/Overview.vue
- frontend/src/layouts/DashboardLayout.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/locales/es.json
- frontend/src/locales/fr.json
- frontend/src/locales/nl.json
- frontend/src/locales/tr.json
> feat(frontend): fix postmigration fix

- frontend/src/assets/News/news.json
- frontend/src/components/Overview/CommunityNews.vue
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- frontend/src/locales/es.json
- frontend/src/locales/fr.json
- frontend/src/locales/nl.json
> feat(frontend): update text

- e2e-tests/cypress.config.ts
> feat(other): increase e2e page load timeout

- docker-compose.test.yml
- docker-compose.yml
- remove docker autostart
- fix inconsistency with mariadb new option name 
- ups.. is not based on master, it is based on #3394
> feat(other): remove docker autostart

- frontend/src/components/Transaction.spec.js
- frontend/src/components/Transaction.vue
- frontend/src/components/TransactionLinks/TransactionLink.spec.js
- frontend/src/locales/de.json
- frontend/src/locales/en.json
show gdt comments in gdt wallet
> feat(frontend): show gdt comments

- backend/src/password/EncryptionWorker.ts
- backend/src/password/EncryptorUtils.ts
> fix(backend): toggle for using worker threads for password encryption

- admin/src/components/ContributionMessages/ContributionMessagesFormular.spec.js
- admin/src/components/ContributionMessages/ContributionMessagesFormular.vue
- admin/src/components/Federation/CommunityVisualizeItem.vue
- admin/src/components/Federation/FederationVisualizeItem.vue
- admin/src/composables/useDateLocale.js
- localize resubmission date in admin with user date
- move code for getting current local object in separate composable
> feat(admin): resubmission date localized

- backend/src/data/PublishName.logic.ts
> feat(backend): patch getUsername in PublishNameLogic 

- admin/Dockerfile
- admin/src/config/schema.js
- admin/vite.config.js
- backend/Dockerfile
- config/src/commonSchema.ts
- config/src/index.ts
- dht-node/Dockerfile
- federation/Dockerfile
- frontend/src/config/schema.js
- frontend/vite.config.js
> fix(frontend): fix problems with dev container

- .github/workflows/test_backend.yml
- backend/src/emails/sendEmailTranslated.test.ts
- backend/src/emails/sendEmailVariants.test.ts
- backend/src/seeds/factory/user.ts
> refactor(backend): test refactor better bun compatibility

- frontend/src/components/UserSettings/UserLocationMap.vue
> feat(backend): switch marker colors of community location and user location

- backend/jest.config.js
- backend/package.json
- backend/src/apis/gms/model/GmsUser.ts
- backend/src/graphql/resolver/ContributionResolver.ts
- backend/src/graphql/resolver/TransactionResolver.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/src/graphql/resolver/util/compareGmsRelevantUserSettings.ts
- backend/src/interactions/updateUnconfirmedContribution/AbstractUnconfirmedContribution.role.ts
- backend/src/interactions/updateUnconfirmedContribution/UnconfirmedContributionUser.role.ts
- backend/src/interactions/updateUnconfirmedContribution/UnconfirmedContributionUserAddMessage.role.ts
- backend/src/seeds/factory/user.ts
- backend/yarn.lock
- config/package.json
- config/yarn.lock
- database/migrations/0086-add_community_location.ts
- database/package.json
- database/yarn.lock
- dht-node/package.json
- dht-node/yarn.lock
- federation/package.json
- federation/yarn.lock
- upgrade to higher typescript version
- upgrade to higher eslint version
- upgrade to higher ts-node version
- fix new eslint errors and warnings
> feat(backend): upgrade typescript

- admin/src/pages/CreationConfirm.vue
> fix(admin): update field key according to changed graphlq request

- frontend/src/components/Contributions/ContributionList.vue
- frontend/src/components/Contributions/ContributionListItem.spec.js
- frontend/src/components/Contributions/ContributionListItem.vue
- frontend/src/pages/Community.vue
- fix bug with calling wrong function on contribution list update (pagination)
- fix warning with missing emit declaration
- fix bug with not updating contribution message list after adding one
> fix(frontend): community messsages reload

- backend/src/apis/humhub/ExportUsers.ts
- backend/src/apis/humhub/__mocks__/syncUser.ts
- backend/src/apis/humhub/compareHumhubUserDbUser.test.ts
- backend/src/apis/humhub/syncUser.test.ts
- backend/src/apis/humhub/syncUser.ts
- backend/src/data/PublishName.logic.ts
- backend/src/graphql/resolver/UserResolver.ts
- backend/src/graphql/resolver/util/syncHumhub.test.ts
- backend/src/graphql/resolver/util/syncHumhub.ts
- backend/test/testSetup.ts
- prevent error if user has changed e-mail in humhub
- prevent also edge case if user has changed e-mail in humhub and alias in wallet
- improve reporting on export humhub users
> fix(backend): humhub sync on edge cases

- frontend/src/graphql/queries.js
- frontend/src/pages/InfoStatistic.vue
based on #3471, so better review and merge #3471 before
> fix(frontend): set explicit page size for admin and moderator user on information page

- backend/src/apis/humhub/syncUser.ts
- backend/src/graphql/resolver/util/syncHumhub.ts
- frontend/src/locales/de.json
- frontend/src/locales/en.json
- make sure that humhub/syncUser can find the existing user at the expected current username and not the old one
- additional fallback in humhub/exportUsers for not expected data sets
- fix not longer valid tooltip
> fix(backend): fix problem with humhub, changing from and to alias

- .vscode/launch.json
- frontend/src/components/LinkInformations/RedeemInformation.vue
- frontend/src/components/LinkInformations/RedeemLoggedOut.vue
- frontend/src/pages/TransactionLink.vue
- frontend/vite.config.mjs
- adjust some lines to bring contribution link back working again
- add launch debug config for using visual studio code for debugging
- activate source maps in develop mode for debugging
> fix(frontend): fix contribution link

- deployment/bare_metal/start.sh
> fix(other): in deploy run only core count tasks with turbo at the same time

- README.md
- admin/package.json
- backend/package.json
- config-schema/package.json
- core/package.json
- database/package.json
- dht-node/package.json
- federation/package.json
- frontend/package.json
- package.json
- shared/package.json
- turbo.json
add clear command for yarn and turbo for easy cleanup node_modules and build in all workspaces
> feat(other): add clear command for yarn and turbo

- e2e-tests/bun.lock
- e2e-tests/playwright/typescript/bun.lock
> fix(other): fix problems with bun and e2e

- .github/workflows/publish.yml
> fix(other): remove mariadb from publish workflow

- frontend/src/layouts/DashboardLayout.vue
- add link to gdd on overview page
- remove link to gdd from transactions page
- remove link to gdt from gdt page
> feat(frontend): add link to gdd in overview

- frontend/src/components/Contributions/ContributionForm.vue
> fix(frontend): decimal comma to point on contribution form

- config-schema/src/log4js-config/coloredContext.ts
- federation/src/graphql/api/1_0/resolver/AuthenticationResolver.ts
- shared/src/schema/base.schema.test.ts
> fix(federation): fix bug
