login_server/src/cpp/tasks/SigningTransaction.cpp
save response.html by community server error into /var/logs/grd_login folder, to have access to it if used with docker (/logs)
=> make response.html better accessible

frontend/.gitignore, frontend/jest.config.js, frontend/package.json
When the unit test run in the frontend, a coverage report is generated. By now, all report formats given by jest are active.
Add the end of the tests the coverage is printed to the console in text format. In the folder coverage are reports in XML, JSON and HTML.
- relates #122
=> feat: Activate Coverage Report For Unit Tests In Frontend

frontend/src/views/Layout/ContentFooter.spec.js, frontend/src/views/Layout/ContentFooter.vue
* remove Gradido in foorline of content footer
* replace link of Gradido-Akademie in copyright line of footer
* test version in copyright line
* test link to member area
- fixes #105
=> fix: Gradido-Akademie in Footer Links to gradido.net

community_server/webroot/.htaccess, docker-compose.override.yml, docker-compose.yml, frontend/.env.dist, frontend/Dockerfile, frontend/package.json, frontend/run/server.js, frontend/server.js, frontend/src/routes/router.js, frontend/src/views/KontoOverview/GddSend.vue, frontend/vue.config.js, nginx/nginx.conf
fixed frontend production docker build & refactored frontend file structure
- frontend server runs on port 3000 by default
- frontend production docker build successfully runs & builds
- frontend production docker build is no longer reachable from the outside
- moved server.js in subfolder run/
nginx fix for vue interface
- localhost/vue resolves to frontend
- localhost:3000/vue resolves to frontend in development
- images are resolved properly
- remaining services are reachable as normal
- fixed image path to be relative instead of absolute
- cleaned nginx config
- fixes #192 (fully fixed)
- fixes #131 (the path will not be configurable it has to many implications and need cross service environment variables. We should switch at a given time from old frontend to new frontend and make an …
=> fix_nginx_docker

frontend/.env.dist, frontend/Dockerfile, frontend/src/config/index.js, frontend/src/routes/router.js, frontend/src/routes/routes.js, frontend/src/views/Pages/Login.vue
turn registration on and off
In the Dockerfile, I specify whether registration is allowed. 
##Register in App  true || false
ENV VUE_APP_ALLOW_REGISTER="true"
const environment = {
...
VUE_APP_ALLOW_REGISTER: process.env.VUE_APP_ALLOW_REGISTER === 'true',
}
if (CONFIG.VUE_APP_ALLOW_REGISTER) {
router.addRoute({
path: '/register',
component: () => import('../views/Pages/Register.vue'),
})
}
=> turn registration on and off

frontend/src/locales/de.json, frontend/src/locales/en.json
THX geändert zu Thank you 
"thx":"Thank you, ",
"send_success":"your transaction was successfully completed"
"thx":"Danke, ",
"send_success":"deine Transaktion wurde erfolgreich ausgeführt"
- fixes #286
=> THX changed to Thank you

frontend/src/views/Layout/DashboardLayout_gdd.vue, frontend/src/views/Pages/AccountOverview.vue, frontend/src/views/Pages/AccountOverview/GddTable.vue, frontend/src/views/Pages/UserProfileTransactionList.vue
* whenever GddTable is rendered by another parent, it triggers an API call to update the transaction list
* track number of transactions as property an have it available in GddTable
is there one?
=> feat: Update Transactions When GddTable Is Rendered

frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/Pages/AccountOverview/GddSend.vue
-  Spelling: Password reset has spelling mistake - zukünftig
-  Spelling: Password reset has GRADIDO in CAPS, should not be caps.
-  Translate: Sprache - en must be Language - en , same for the German equivalent
-  Translate: Login heading is not translated should be Anmeldung
-  Design: On the 3. Send GDD page there is two horizontal lines below the "Thanks... [Button]" part. Remove one.
teil von : #350
=> spelling & translation

frontend/src/apis/communityAPI.js
As we do not have pagination so far, we request 1000 transactions, to make sure, the user sees all transactions.
=> fix: Set Maximum Transactions Loaded  to 1000

frontend/src/apis/communityAPI.js, frontend/src/views/Pages/AccountOverview.spec.js, frontend/src/views/Pages/AccountOverview.vue, frontend/src/views/Pages/AccountOverview/GddSend.spec.js, frontend/src/views/Pages/AccountOverview/GddSend.vue, frontend/src/views/Pages/AccountOverview/GddSend/QrCode.vue, frontend/src/views/Pages/AccountOverview/GddSend/TransactionConfirmation.vue, frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.spec.js, frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue, frontend/src/views/Pages/AccountOverview/GddSend/TransactionResult.vue
* Make components out of the huge GddSend component
* fixes #416 
* gets rid of the boolean logic by the use of named slots
* all the transaction logic is now in `AccountOverview.vue`, so may be we should rename this component as it actually manages the transactions. Any ideas?
* all other components involved are stupid, except of `TransactionForm.vue` which handles the validation.
=> refactor: Split GddSend into Components

community_server/src/Controller/AppRequestsController.php
fix sorting of transaction list if more transactions exist as requested.
By the way I have see that count return only the with limit retrieved transactions + decay transaction.
I have changed it so that it returns the total count of transactions in which the user is involved. Without decay transaction, because they are generated on the fly and not saved in db. 
- fixes #398
=> fix sorting and use total count

login_server/src/cpp/JSONInterface/JsonCreateTransaction.cpp, login_server/src/cpp/model/Session.cpp, login_server/src/cpp/model/Session.h, login_server/src/cpp/model/gradido/Transaction.cpp, login_server/src/cpp/model/gradido/Transaction.h
- store last transaction in session (in memory)
- compare transaction with last sended transaction
- return error if last transaction are the same as new transaction only if new transaction is within 100 seconds of the old transaction
- fixes #495
=> compare with last transaction sended

frontend/src/i18n.js, frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue
Do not show the dividers of numbers > 1000. E.g show `12345.00` instead of `12,345.00`
=> fix: Thousend Dividers on GDD Send Amount Field

frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.spec.js, frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue, frontend/src/views/Pages/UserProfile/UserCard.vue, frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue, frontend/src/views/Pages/UserProfileOverview.spec.js, frontend/src/views/Pages/UserProfileOverview.vue
border to send input fields from gdd. 
components that are not used in the profile are disabled until used.
=> Hide unuse components in profil

community_server/src/Template/Email/text/notification_transfer.ctp
Because of problems with strato I have removed the reply-to transaction sender function in Gradido Transfer transaction commit E-Mails and update the text instead such that the Email Address from Sender of the Gradido Transaction is sended in E-Mail text.
=> update transfer email text

frontend/src/apis/loginAPI.js
The server does not accept an empty description for the user profile. As we do not use description so far, it is always empty. This means, that the user profile cannot be updated.
- relates #616
=> fix: Do Not Pass Userdata Description to Server

login_server/src/cpp/JSONInterface/JsonUpdateUserInfos.cpp
Allow empty description for updateUserInfos.
If in db a description entry exist and and empty description field will be transfered,
description in db will be emptied also!
- fixes #616
=> Allow empty description

community_server/src/Model/Table/TransactionsTable.php
Fix crash occuring if no decay block is set and community server tries to call getTimestamp on a nullptr. 
- fixes #639
=> check for null date

community_server/src/Model/Table/TransactionsTable.php, login_server/src/cpp/SingletonManager/PendingTasksManager.cpp, login_server/src/cpp/SingletonManager/PendingTasksManager.h, login_server/src/cpp/controller/EmailVerificationCode.cpp, login_server/src/cpp/controller/User.cpp, login_server/src/cpp/model/gradido/Transaction.cpp, login_server/src/cpp/model/table/AppAccessToken.h, login_server/src/cpp/model/table/ElopageBuy.h, login_server/src/cpp/model/table/EmailOptIn.h, login_server/src/cpp/model/table/Group.h, login_server/src/cpp/model/table/ModelBase.h, login_server/src/cpp/model/table/PendingTask.h, login_server/src/cpp/model/table/User.h, login_server/src/cpp/model/table/UserBackup.h, login_server/src/cpp/model/table/UserRole.h, login_server/src/cpsp/CheckTransaction.cpsp, login_server/src/cpsp/UserUpdateGroup.cpsp
Fix bugs which let the login-server crash
- Change Pending Task structure from using virtual objects to combine different classes with the base class into on map, to using only direct the model::gradido::Transaction class. With that change, it isn't neccessary anymore to make dynamic casts of pointers which seems to lead to bugs with the Poco::AutoPtr. The Hedera Transactions are not longer needed so it is relative easy.
- Move all Destructors from mode::table classes from public to protected to prevent misuse of the table classes ignoring the reference counting (needed for Poco::AutoPtr)
- depends on / includes  #640
=> Login fix crash

.github/workflows/test.yml, frontend/src/components/DecayInformation.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/Pages/AccountOverview/GddSend/TransactionConfirmation.vue, frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.spec.js, frontend/src/views/Pages/AccountOverview/GddSend/TransactionForm.vue, frontend/src/views/Pages/AccountOverview/GddTransactionList.spec.js, frontend/src/views/Pages/AccountOverview/GddTransactionList.vue, frontend/src/views/Pages/ForgotPassword.vue
frontend text improvemets
- forgotPassword: Change text of button from Send now to  Jetzt senden
- Email field in send GDD form must be called: Recipient
- Only Message, Nachricht as label for the memo field of the send Gdd form
- Transaction list, von, an and Nachricht is not localized. Uhr must be removed
- Minus sign before the decay value in the detail view of a transaction.
- memo text of transaction should always be shown
- Content menu english: Members area (remove ')
PLUS ... I could not leave it ... 
is only changed the html
-  #630 
- #597 
- #591
=> 630 frontend text improvemets

community_server/src/Model/Table/TransactionsTable.php, community_server/tests/TestCase/Controller/AppRequestControllerTest.php
Currently the creation transaction will be shown with delay between targe_date and received, but we've decided to use the recevied as start date for decay the same as by transfer transactions. 
I had already updated the code, but i've forgott that for the api call the decay will be calculated seperatly. 
I have now remove this line. 
- fixes #644
=> fix display error with creation

login_server/src/cpp/SingletonManager/SessionManager.cpp
Until now first- and last names need to have at least 3 characters. 
But now someone has tried to registered with "Jo" as his first name. 
So I changed the rule for names validation to have at least 2 characters.
=> Login-Server bug fix, allow names with 2 characters also

login_server/src/cpp/HTTPInterface/PageRequestMessagedHandler.cpp, login_server/src/cpp/HTTPInterface/PageRequestMessagedHandler.h, login_server/src/cpsp/Login.cpsp
Vom Support habe ich die Meldung bekommen das die Passwort zurücksetzen Funktion im altend frontend nicht mehr funktioniert.
Eine Analyse hat ergeben, das dies durch mein Bugfix am 15.07 ans Licht gekommen ist.
Sie hat davor nur durch einen unbeabsichtigten Side-Effect funktioniert. 
Ich hatte damals dummerweise versucht den Passwort reset und das Email aktivieren ohne redirects umzusetzen,
was das ganze sehr kompliziert und fehleranfällig gemacht hat. 
Daher sehe ich jetzt davon ab das zu fixen, bzw. zu refactoren und lege stattdessen den "Paswort vergessen" Link vom alten Frontend auf die entsprechende Seite vom neuen Frontend. 
Ja Ulf, ich gebe endlich zu das ich beim Login-Server einige Konzeptionsfehler gemacht habe, was ihn in bestimmten Bereichen fehleranfällig gemacht hat. Ich …
=> bugfix: change to new frontend passwort reset

frontend/src/components/DecayInformation.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
decay with the value 0 is no longer displayed. 
the button is no longer displayed and there is no additional information about a transaction.
- fixes #758
=> decay with the value 0 is no longer displayed

backend/src/index.ts, docker-compose.override.yml
This PR fixes two problems which came to light after running the database tool on an external environment (alex):
- if the old migration table is present selecting `fileName` will result in an SQL error
- when building in development environment the docker container contains the built files, but files are read from local harddrive where the build folder is not present. We mount a drive for the build folder in development mode. This happens since we always use the built variant of the database project since the table contains the filename - which then varies between js & ts (it is unclear how this will affect development on this tool, but in most cases one will use a clean database and use the `yarn dev_up/down/reset` commands which will use the `.ts` file endings - therefore its …
=> fix_database_migrations

community_server/src/Template/StateBalances/overview_gdt.ctp
Multiplicate gdt entry with 100 to get expected gdt in cent.
The View is calling a function (element) for make decimal from cent + format for showing gdt and this function is used also 
somewhere else so I cannot simply remove the "/ 100 " call from it. 
Not nice but a we work to remove community server complete, I think it is ok. 
- fixes #784
=> Fix Bug in displaying GDT in Old frontend

nginx/Dockerfile, skeema/Dockerfile
- downgrade nginx to old version, nginx:latest return 400 Bad Request if Login-Server make request to Community-Server
- upgrade skeema, old version don't install any longer
A fresh docker build don't work anymore
=> update docker files

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/devops_ticket.md, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/refactor_ticket.md, .github/ISSUE_TEMPLATE/release.md, .github/PULL_REQUEST_TEMPLATE.md
- remove discord links from templates
- make the templates project agnostic
- link to the new repo https://github.com/ulfgebhardt/issue-templates to have it compatible
- rename refactor tickets into .. ticket
- None
=> Remove discord link for issue templates

login_server/src/cpp/ServerConfig.cpp, login_server/src/cpp/ServerConfig.h, login_server/src/cpp/model/gradido/Transaction.cpp
Login-Server try to resend not finished transaction on restart again.
The reason from the start was that no transactions get's lost by server crash. 
But in production this lead to creation transaction which are invalid because the user has already get enough Gradidos,
resend every time if login-server is startet new. And therefore send again the error message confusing the creator.
Make it optional with additional option in config with default false.
Removed double code which seems to resulting from some merge or rebase in past
=> disable auto-resend of not finished transactions on login-server restart

docker-compose.override.yml, docker-compose.yml, skeema/Dockerfile
Mount sql files folder which skeema is checking for db schema updates dynamic instead of copy it in build. 
So it isn't any longer necessary to rebuild skeema after login-server db was changed. 
The .skeema files are config files necessary for skeema to work.
=> docker skeema: mount sql files folder dynamic

.github/workflows/test.yml, database/src/prepare.ts
The community-server needs for testing in github workflow a db.
Until now a mariadb docker container was used, exported for testing gradido/mariadb:test
After the community-server sql files was removed from this config it don't longer work, after updating this container. 
So now we must use this new db migration container. 
Without this update, after the next change in community-server db tests will fail. 
Like in #831 
- removed some debugging stuff from github workflow
=> Community-Server Test with new db migration

backend/src/jwt/decode.ts, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/main.js
Server raises error with message: `'403.13 - Client certificate revoked'` when JWT has expired.
Frontend checks each response for this error. When it is present, redirect to login. The message is translated and toasted by the apollo call.
- fixes #827
=> feat: Redirect to Login when JWT has expired

frontend/src/validation-rules.js, frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.spec.js
When white space is entered in any set password field, a validation error is shown correctly.
=> fix: Whitespace in Password Shows Validation Error

frontend/src/views/Layout/DashboardLayout_gdd.spec.js, frontend/src/views/Layout/DashboardLayout_gdd.vue
Logout requires authentication. If the Jwt is expired, an error is thrown in the backend. This triggers a redirect to login. The catch block in the logout call triggers the same redirect, which causes a vue error. Now this redirect is only triggered when we are not already on the login page.
=> fix: Double Redirect After Logout with Expired JWT

frontend/src/components/SidebarPlugin/SideBar.spec.js
Test behavior of Sidebar Menu with the default publisher ID and no elopage
=> fix: Test Default Publisher ID in Sidebar Menu

community_server/src/Controller/ServerUsersController.php
For develop I had made open the community server user account creation and had manually removed it in release builds on production. But it is to easy to forget it, so now it will default off and must be enabled in development to create server user for creation. 
- fixes #1071
=> fix open community server user account creation

backend/src/graphql/resolver/TransactionResolver.ts
replace implementation of `getPublicKey` to no longer require the sessionId. Furthermore the call now no longer calls `getUserInfos` on the `login_server` but just queries the database itself
This is actually not an implementation of `getUserInfos` since we do not need that, but just the publicKey part
- None
=> login_call_getUserInfos

.github/workflows/test.yml, admin/src/graphql/verifyLogin.js, admin/src/main.js, admin/src/router/guards.js, admin/src/router/guards.test.js, admin/src/store/store.js, admin/src/store/store.test.js
* Calls `verifyLogin` on `/authenticate`
* commits the response to the store, when user has admin rights
* makes sure that moderator is present in store on every route
=> feat: Verify Login in Admin Interface

backend/src/graphql/resolver/AdminResolver.ts, backend/src/graphql/resolver/TransactionResolver.ts
We had a discrepance between old admin interface and new one, when we stored the balance value in state_user_transactions we were missing 0000.
Update of a pendingCreation had also wrong display. 
- None
=> Withdrew * 10000 and / 10000 since we need to store the full value.

backend/src/server/createServer.ts, database/entity/0001-init_db/User.ts, database/entity/0002-add_settings/User.ts, database/entity/0006-login_users_collation/LoginUser.ts, database/entity/LoginUser.ts, database/migrations/0002-add_settings.ts, database/migrations/0003-login_server_tables.ts, database/migrations/0004-login_server_data.ts, database/migrations/0005-admin_tables.ts, database/migrations/0006-login_users_collation.ts
Besides some documentary refactoring this migrates the database to an explicit `DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci` which was set on `state_users` (and not modeled yet), but not on `login_users`. This resulted in both fields not being comparable if the database charset was not exactly the given charset and collation.
This PR:
- Migrates the Database to specify the charset and collation for both tables explicitly
- Migrates the entity models to reflect the database model more precisely
- Documents the purpose of all existing migrations in a proper manner
- None
=> migration_0006_login_users_collation

admin/src/components/ConfirmRegisterMailFormular.spec.js, admin/src/components/ConfirmRegisterMailFormular.vue, admin/src/components/UserTable.vue, admin/src/locales/de.json, admin/src/locales/en.json
1. Wenn eine E-Mail bestätigt ist dann wir d nur der Text und Datum der bestätigung angezeigt. 
2. Wenn nicht bestätigt ist, wird das formular angezeigt mit dem erneuten absenden einer mail funktion zum bestätignen der email. 
- fixes #1230
=> 1230 details für wiederholte email bestaetigen versenden

admin/src/components/UserTable.vue
Wenn ich in der Nutzer Suche seite bin und für einen einzelnen Nutzer dei row details geöffnet habe .. und dann auf die mehrfachschöpfungsseite wechsel, schliest es die row-details autoamtisch. bzw. wird es weggeklemmt wenn der jeweilige page.type aktualiesert. 
bei der mehrfachschöpfung sollten alle row-details nicht zu öffnen sein .. und wenn offen .. sollen sie nicht angezeigt werden. 
- fixes #1234
=> close row-details automatically when switching to multiple creation page

backend/src/server/plugins.ts
Use `set` instead of `append` when a key already exists in response header.
- fixes #1254
=> fix: Override Existing Token in Response Header

admin/.env.dist, admin/src/components/NavBar.spec.js, admin/src/components/NavBar.vue, admin/src/config/index.js
When admin user logout they are send to a 404 not found, now redirects to the wallet-login page
- fixes #1241
=> Admin Logout redirectes to the wallet login page.

frontend/src/views/Layout/AuthLayout_gdd.spec.js, frontend/src/views/Layout/AuthLayout_gdd.vue
LanguageSwitch & LanguageSwitchSelect components doesn't update each other but both change the language of the website. So if LanguageSwitch is set to english the languageSwitchSelect stays on german and vise versa.
- fixes #1247
=> Don't show the language-switch on the /register page.

frontend/src/components/Menu/Navbar.spec.js, frontend/src/components/Menu/Navbar.vue, frontend/src/views/Layout/DashboardLayout_gdd.vue
The balance in the navigation bar is localized and always with 2 digits.
=> fix: Render Localized Balance in NavBar

frontend/src/assets/scss/custom/gradido-custom/_buttons.scss, frontend/src/views/Pages/Register.vue
add 
`.btn-outline-secondary {
color: #4385b1 !important; 
}`
in 
frontend/src/assets/scss/custom/gradido-custom/_buttons.scss
=> add .btn-outline-secondary in scss

backend/src/config/index.ts, backend/src/webhook/elopage.ts, database/entity/0003-login_server_tables/LoginElopageBuys.ts, database/entity/0021-elopagebuys_fields_nullable/LoginElopageBuys.ts, database/entity/LoginElopageBuys.ts, database/migrations/0021-elopagebuys_fields_nullable.ts
Fixes a crash which occurs on production due to a field not reliable being an integer delivered by elopage. In order to fix this we check if the parsed fields are actually parsable as integer and make the fields in the database nullable. Exception is the price, here we write 0 if we cannot parse it.
- fixes #1473
=> Fix: Elopage Hook Crash

backend/src/config/index.ts, backend/src/graphql/resolver/UserResolver.ts, database/migrations/0025-emails_to_lower.ts
This fixes a bug where users who registered with uppercase letters in their email not being able to login even after password reset.
This affected 20 users on production, of which 7 were test accounts. Of the 13 users one was from early 2020, while the remaining 12 were the earliest from 16.10.2021. This means this bug was introduced with the switch to Apollo.
- Corrects existing users in the database
- Fixes the register call to properly sanitize user input
Sideeffect:
- Since the email is part of our password generation mechanism this PR will invalidate the passwords of affected users (20). Those have to reset their passwords to regain access to their account.
1. Check out `master`
2. Register with `sPoNgEbOb@wHaTeVeR.oCeAn`
3. Try login  -> should fail, even when typing the email in …
=> Fix: Upper case email on register breaks account

frontend/src/components/Transactions/TransactionCreation.vue
community name in creation transaction is displayed cleanly
- fixes #1577
=> community name in creation transaction is displayed cleanly

backend/src/config/index.ts, backend/src/graphql/model/Transaction.ts, backend/src/graphql/resolver/TransactionLinkResolver.ts, backend/src/graphql/resolver/TransactionResolver.ts, database/entity/0032-add-transaction-link-to-transaction/Transaction.ts, database/entity/Transaction.ts, database/migrations/0032-add-transaction-link-to-transaction.ts
Adds new column `transaction_link_id` to transactions table. This field is filled by the ID of an transaction link when the transaction is created by redeeming a link.
- fixes #1593 
- fixes #1592
=> feat: Link Transaction to Transaction Link on Redeem

backend/jest.config.js, backend/package.json, backend/src/server/createServer.ts, backend/tsconfig.json, backend/yarn.lock
- use tsconfig-paths package to resolve paths
- link build and src paths for the external database package
- some timezone stuff
- fix jest when `build/` folder is present 
- None
1. For me running `yarn build` on backend produces `build/`-folders in `backend/` and `database/`
2. Running `yarn dev` in `backend/` has the server properly started
3. Running `yarn start` in `backend/` has the server properly started
Is this fixing your issue @Mogge ?
=> Fix: build for development and production links external modules properly

frontend/src/components/GddTransactionList.vue, frontend/src/components/Menu/Navbar.vue, frontend/src/components/Status.spec.js, frontend/src/components/Status.vue, frontend/src/pages/Overview.vue
an animated icon is displayed if no balance has been loaded yet. this affects the balance in the navbar, the balnaceim status and the start text in the overview. 
- fixes #1729 
https://user-images.githubusercontent.com/1324583/161424839-b5d56ee9-c204-4708-abc5-11c0a8396217.mp4
=> 1729 load spinner if pending balance

frontend/src/config/index.js
The date for the decay start block was set to UTC 0000 so that no time offset occurs and the date can be recognised cleanly so that the startDecayBlock can be found and displayed. 
- fixes #1805
=> change config DECAY_START_TIME in UTC  0000

backend/src/config/index.ts, backend/src/graphql/resolver/AdminResolver.test.ts, backend/src/graphql/resolver/AdminResolver.ts, database/entity/0036-unique_previous_in_transactions/Transaction.ts, database/entity/Transaction.ts, database/migrations/0036-unique_previous_in_transactions.ts
To ensure that the ID of the previous transaction is unique, add unique to previous column.
The reason is, that when transactions are fired in milliseconds intervals, the wrong previous id is selected.
- None
=> fix: Unique Previous Column in Transactions Table

backend/src/graphql/resolver/ContributionResolver.test.ts, backend/src/graphql/resolver/ContributionResolver.ts
Checks if the memo length that is send to createContribution & updateContribution mutation is correct (greater than 5 and smaller than 255 chars)
- fixes #2076
=> Fix: Test memo length on createContribution & updateContribution

frontend/src/components/ClipboardCopy.vue, frontend/src/components/GddSend/TransactionResultLink.vue, frontend/src/components/TransactionLinks/TransactionLink.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/pages/Send.spec.js, frontend/src/pages/Send.vue
When sending Gradido via link, now the user can get the QR code, just copy the link to the clipboard, and copy the link, username, amount, and memo text by clicking a button.
- fixes #2077
=> Enable copying the link, username, amount, and memo text after transaction link creation

frontend/src/components/ContentFooter.spec.js, frontend/src/components/ContentFooter.vue, frontend/src/components/Menu/Navbar.spec.js, frontend/src/components/Menu/Navbar.vue, frontend/src/components/Menu/Sidebar.spec.js, frontend/src/components/Menu/Sidebar.vue
The meber area entry is not displayed in the footer and not in the menu, if the user has no elopage account.
- fixes #2094
=> Remove member area from menu (desktop and mobile), when user has no elopage account

frontend/src/components/TransactionLinks/TransactionLink.spec.js, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/locales/es.json, frontend/src/locales/fr.json, frontend/src/locales/nl.json, frontend/src/mixins/copyLinks.js, frontend/src/pages/Send.spec.js
Add the following hint to the redeem/transaction link text, when using the fucntion "copy link and text":
_DE: Achtung: Jeder kann diesen Link einlösen. Gib ihn bitte nicht weiter!
EN: Attention: Anyone can redeem this link. Please do not share it!
ES: Atención: cualquiera puede canjear este enlace. Por favor, no lo transmitan.
FR: Attention : tout le monde peut utiliser ce lien. Ne le partage pas, s'il te plaît !
NL: Attentie: Iedereen kan deze link inwisselen. Geef het alsjeblieft niet door!_
- fixes #2151
=> 2151 add hint to redeem link

admin/src/components/ContributionMessages/slots/ContributionMessagesListItem.vue, admin/src/graphql/listContributionMessages.js
As Moderator I want to see every message from moderators on the right side so we have a better overview of message from moderators and from users.
- None
=> fix: 🍰 isModerator on messages to switch the messages side in the messages overview

backend/src/graphql/resolver/AdminResolver.test.ts, backend/src/graphql/resolver/AdminResolver.ts, backend/src/graphql/resolver/ContributionResolver.test.ts, backend/src/graphql/resolver/ContributionResolver.ts
The tests of the admin resolver shows clearly, that changing the month of a existing contribution is not working as expected. Therefore it is disabled for users in the wallet as well as for admins
- None
=> fix: 🍰 Disable Change Of Month For Update Contribution (wallet and admin)

backend/src/typeorm/repository/User.ts
When searching for users in the admin interface that have a deleted email contact, an error is thrown. Include the deleted email contacts in the left join.
- fixes #2280
=> fix: Include Deleted Email Contacts in User Search

.github/workflows/test.yml
Our Github workflows get the warning
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/upload-artifact, actions/checkout
related to the actions `actions/checkout@v2` and `actions/upload-artifact@v2` utilized in our workflows.
These are easy fixed by using their API version 3.
=> Github workflow: update actions to the current API version using Node v 16

frontend/src/components/Contributions/ContributionList.vue, frontend/src/components/Contributions/ContributionListItem.spec.js, frontend/src/components/Contributions/ContributionListItem.vue, frontend/src/pages/Community.vue
when i change the tab it closes all open tabs from the child elements. 
if i have a message box open within the contribution list and want to open another one, it also closes the open one first.
- fixes #2380
=> fix(frontend): close all open collapse by change tabs in community

backend/src/graphql/resolver/util/creations.test.ts
It looks like `setTimeout` hast problems with higher values in jest. Therefore run two timers.
- None
=> fix(backend): run all timers for high values

backend/src/federation/index.test.ts
Setup unit tests for federation.
Events can be triggered as shown. Different event arguments can be applied to simulate different cases. 
- None
=> feat(backend): setup unit tests for federation

.github/workflows/test.yml
The nginx build does not depend on other builds in the test workflow.
So the build does not need to wait for other builds finishing.
- fixes #2457
=> refactor(other):  build nginx docker image in workflow independent of other builds

admin/src/components/DeletedUserFormular.vue
In the admin frontend's user search, when undeleting a user the succes toast was triggered twice
- in the compoment `UndeletedUserFormular`
Here the success toast was inconsistently triggered only for undeletion, but not for deletion of a user, so it has been removed here to fix the issue.
- on the page `UserSearch`
Here the success toast is triggered more globally for admin actions like user deletion/undeletion in the user entry.
- fixes #2435 2435
=> fix(admin): reduce triggers of success toast on deleted user form to exactly one

frontend/src/components/Inputs/InputEmail.vue, frontend/src/pages/ForgotPassword.spec.js, frontend/src/pages/ForgotPassword.vue, frontend/src/pages/Login.spec.js, frontend/src/pages/Login.vue, frontend/src/pages/Register.spec.js, frontend/src/pages/Register.vue
InputEmail label and placeholder are displayed correctly per language
- fixes #2474
=> fix(frontend): input-email label and placeholder are displayed correctly per language

frontend/src/pages/Transactions.vue
Gdt datas were not loaded when transaction component was loaded. Add a watch on gdt switch so if set on true we load gdt datas.
- None
=> fix(frontend): add a watch on gdt prop to assure propper loading when mounted

backend/src/graphql/resolver/EmailOptinCodes.test.ts, backend/src/graphql/resolver/UserResolver.test.ts, backend/src/graphql/resolver/UserResolver.ts
The user resolver's error message for `forgotPAssword` requests in case the email cannot be resend contained the unit of time twice.
=> refactor(backend): refine assembly of error message in user resolver

frontend/src/components/DecayInformations/DecayInformation-Long.vue, frontend/src/components/TransactionRows/DurationRow.vue
Transaction info, right-justified, so that the commas of the amounts are below each other.
- fixes #1006
=> refactor(frontend): transaction info, right-justified, so that the commas

backend/.eslintrc.js, backend/src/federation/client/Client_1_1.ts, backend/src/federation/client/FederationClient.ts, backend/src/federation/client/FederationClient_1_0.ts, backend/src/federation/client/FederationClient_1_1.ts, backend/src/federation/validateCommunities.test.ts, backend/src/federation/validateCommunities.ts
This PR defines a camelcase exception for the FederationClient to be suffixed by the Version without requiring an camelcase exception every time. We define a global exception.
Furthermore the Client_XX_X is renamed to FederationClient_XX_X to avoid potential conflicts where the camelcase rule should not be taking place.
- fixes https://github.com/gradido/gradido/issues/2997
=> refactor(backend): camelcase exception for FederationClient_XX_X

frontend/src/components/CommunitySwitch.vue
In my tests, an empty line was constantly displayed, which broke the design, so I had made the first element invisible via css. But this empty line does not seem to exist anymore and my CSS statement now leads to problems that the first community is not visible. So this PR remove this css to show all options of community switch. 
- None
=> fix(frontend): make invisible community visible

backend/src/graphql/arg/Paginated.ts, backend/src/graphql/resolver/util/findContributions.ts
It seems default value in graphql/arg/Paginated overwrite default values which are used in various places in resolvers.
In searchAdminUsers default value is set to 25 was overwritten by 3 in Paginated. The frontend call searchAdminUsers without parameters so it gets only the default count of results.
TODO: Rethink pagination mechanism in light of larger communities. Not all places can handle more than one page results.
=> fix(frontend): fix to less moderator/admins on information page

backend/package.json, backend/yarn.lock, database/package.json, database/yarn.lock
Fix backend and database build error on windows.
It is triggered by the use of mkdir -p and cp which do not exist under Windows. The solution is to use the npm packages mkdirp and ncp which were created exactly for this purpose.
=> feat(workflow): fix backend and database build error on windows

backend/src/config/index.ts, database/entity/0075-contribution_message_add_index/ContributionMessage.ts, database/entity/ContributionMessage.ts, database/migrations/0075-contribution_message_add_index.ts, dht-node/src/config/index.ts, federation/src/config/index.ts
Bernd notice a slowdown of admin interface in production.
I measure 4 seconds of list confirmed contributions (limit 25) query and 4 additional seconds for counting the total confirmed contributions.
With a production db copy on my dev pc I have still 3 seconds per query.
After adding only one index to db, for contribution_messages.contribution_id
the time duration is down to ~40 ms for each query.
=> refactor(database): add index to contribution_message

admin/src/components/ContributionMessages/ContributionMessagesFormular.spec.js, admin/src/components/ContributionMessages/ContributionMessagesFormular.vue, admin/src/components/ContributionMessages/ContributionMessagesList.spec.js, admin/src/components/ContributionMessages/ContributionMessagesList.vue, admin/src/components/Tables/OpenCreationsTable.spec.js, admin/src/components/Tables/OpenCreationsTable.vue, admin/src/components/input/TimePicker.spec.js, admin/src/components/input/TimePicker.vue, admin/src/graphql/adminCreateContributionMessage.js, admin/src/graphql/adminListContributions.js, admin/src/locales/de.json, admin/src/locales/en.json, admin/src/pages/CreationConfirm.spec.js, admin/src/pages/CreationConfirm.vue, admin/src/pages/Overview.spec.js, admin/src/pages/Overview.vue, backend/src/config/index.ts, backend/src/data/ContributionMessage.builder.ts, backend/src/graphql/arg/ContributionMessageArgs.ts, backend/src/graphql/arg/SearchContributionsFilterArgs.ts, backend/src/graphql/resolver/ContributionMessageResolver.ts, backend/src/graphql/resolver/util/findContributions.ts, database/entity/0077-add_resubmission_date_contribution_message/ContributionMessage.ts, database/entity/ContributionMessage.ts, database/migrations/0077-add_resubmission_date_contribution_message.ts, dht-node/src/config/index.ts, federation/src/config/index.ts, frontend/src/components/ContributionMessages/ContributionMessagesListItem.vue
Select a date on which the contribution should be displayed again. Until then it will be hidden in default mode. But you can display it at any time by unchecking the checkbox for resubmission. 
- update findContributions query builder 
- add checkbox to admin underneath checkbox for hashtag
- add signal which will be emitted after adding comment to contribution which set resubmission date for updating contribution list
- add resubmission_at date to contribution_messages table and entity and ContributionMessageArgs
- add props to ContributionMessagesFormular for accessing checkbox for hiding resubmission to only update contribution list after adding resubmission date if resubmission should be hided 
- update frontend to show "moderator has edited contribution" in histories messages if …
=> feat(admin): resubmission

deployment/bare_metal/nginx/common/limit_requests.conf, deployment/bare_metal/nginx/sites-available/gradido.conf.ssl.template, deployment/bare_metal/nginx/sites-available/gradido.conf.template, deployment/bare_metal/nginx/sites-available/update-page.conf.ssl.template, deployment/bare_metal/nginx/sites-available/update-page.conf.template, deployment/hetzner_cloud/cloudConfig.yaml, deployment/hetzner_cloud/install.sh
- correct position of include /etc/nginx/common/limit_requests.conf; cannot be inside server, at lest in newer nginx version
- fix fail2ban, don't start out of the box on debian 12
- fail2ban, enable nginx-bad-request and nginx-limit-req filter
=> fix(other): deployment bugfixes

backend/src/config/index.ts, backend/src/federation/validateCommunities.ts
FEDERATION_VALIDATE_COMMUNITY_TIMER: 
Number(process.env.FEDERATION_VALIDATE_COMMUNITY_TIMER) `??`  60000,
lead to FEDERATION_VALIDATE_COMMUNITY_TIMER = NaN if process.env.FEDERATION_VALIDATE_COMMUNITY_TIMER wasn't set. That lead to continuously running validate communities, put one CPU Core to 100% all time and fill the hdd with logs.
So to prevent this, changing back FEDERATION_VALIDATE_COMMUNITY_TIMER: 
Number(process.env.FEDERATION_VALIDATE_COMMUNITY_TIMER) `||` 60000
and add additional check for positive number before running validate communities.
=> fix(backend): prevent running validate communities continuous

deployment/hetzner_cloud/install.sh
A Customer run into an error while trying to setup gradido community.
I have given him a fix_install.sh 
fix_install.sh:
```bash
#!/bin/bash
if [ -z "$1" ]; then
echo "Usage: Please provide a branch name as the first argument."
exit 1
fi
set -o allexport
SCRIPT_PATH=$(realpath ../bare_metal)
SCRIPT_DIR=$(dirname $SCRIPT_PATH)
LOCAL_SCRIPT_PATH=$(realpath $0)
LOCAL_SCRIPT_DIR=$(dirname $LOCAL_SCRIPT_PATH)
PROJECT_ROOT=$SCRIPT_DIR/..
set +o allexport
if [ -f "$SCRIPT_PATH/.env" ]; then
set -o allexport
source $SCRIPT_PATH/.env
set +o allexport
else
set -o allexport
source $SCRIPT_PATH/.env.dist
set +o allexport
fi
export DB_USER=gradido
export DB_PASSWORD=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c 32; echo);
mysql <<EOFMYSQL
ALTER USER '$DB_USER'@'localhost' IDENTIFIED BY …
```
=> fix(other): deployment bugfixes 

deployment/bare_metal/.env.dist
Every Option in one of the .env.templates written this way:
`NEW_OPTION=$NEW_OPTION`
Must have an entry like this in deployment/bare_metal/.env.dist with there default value
`NEW_OPTION=false`
Especially for the vue modules.
If this is missing, on running start.sh 
`NEW_OPTION=$NEW_OPTION`
will be copied in .env, leading to this build error:
=> fix(other): add GMS_ACTIVE and GMS_URL to deploy .env.dist

frontend/src/components/Menu/Sidebar.spec.js, frontend/src/components/Menu/Sidebar.vue
- remove GDT Entry in sidebar
- detect of gdt link in transactions was clicked and mark menu item `transacions` as active
=> feat(frontend): remove gdt menu entry

backend/src/graphql/resolver/ContributionResolver.test.ts, backend/src/graphql/resolver/util/creations.test.ts, backend/src/graphql/resolver/util/creations.ts, backend/src/util/utilities.test.ts, backend/src/util/utilities.ts
This pull request addresses an issue with date calculations in our codebase, specifically when subtracting months from dates that fall at the end of a month, such as 31st May or 31st July. The previous method using Date.prototype.setMonth resulted in erroneous outcomes. For instance, subtracting three months from 31st May yielded March instead of February. This new function ensures that the correct month is calculated by setting the day to the 1st before performing the month subtraction.
=> fix(backend): fix test which will only fail at 31. of month, or 30.05

backend/src/apis/humhub/HumHubClient.ts, backend/src/apis/humhub/model/Profile.ts, backend/src/graphql/resolver/UserResolver.ts, frontend/src/pages/Circles.spec.js, frontend/src/pages/Circles.vue
- gradido_address on humub link always set to gradido_id
- increase humhub JWT Token Timeout to the same like wallet login
- static humhub link on circles page instead of invoking window.open, hopefully that fix the problem with safari on mac
- add try catch in user login in case humhub server isn't reachable or jwt secret isn't correct
=> feat(frontend): more compatible humhub auto-login link

backend/src/config/index.ts, backend/src/graphql/resolver/BalanceResolver.ts, backend/src/graphql/resolver/TransactionResolver.ts, backend/src/logging/BalanceLogging.view.ts, backend/src/logging/DecayLogging.view.ts, backend/src/server/context.ts, database/migrations/0082-introduce_gms_registration.ts, database/migrations/0085-add_index_transactions_user_id.ts, dht-node/src/config/index.ts, federation/src/config/index.ts
- make TransactionResolver.transactionList faster, improvement on stage2.gradido.net from ~350 ms to ~100 ms with production data set copy
- calling gdt server for gdt sum parallel to rest of transactionList logic
- calling seems to be needing at least 100 ms, independent of gdt server speed (return balance in 15 ms)
- adding INDEX for transactions.user_id improve speed for getLastTransaction and getTransactionList dramatic
- getLastTransaction from ~127 ms to 4 ms
- getTransactionList ~300 ms to 14 ms
- reduce log output from decimal in BalanceResolver.balance with added DecayLoggingView and BalanceLoggingView
=> feat(backend): speedup listTransactions

admin/src/graphql/createContributionLink.js
Due issues connected with `maxAmountPerMonth` value used earlier in contribution link creation prop is now removed from gql.
=> fix(admin): fix create contribution link

backend/src/config/index.ts, backend/src/graphql/resolver/UserResolver.ts, database/migrations/0087-add_index_on_user_roles.ts, dht-node/src/config/index.ts, federation/src/config/index.ts
- let mariadb join user and user_roles table instead of two separate db calls from nodeJs
- add user_id index in user_roles to prevent slow down if user_roles table has much more entries as today
=> feat(backend): optimize find user query on login

.github/workflows/publish.yml, .github/workflows/test_dht_node.yml, .github/workflows/test_dlt_connector.yml, .github/workflows/test_e2e.yml, .github/workflows/test_federation.yml
github download- and upload artifact v3 and below are depracted and randomly don't work, so we must update to v4
=> refactor(workflow): increaste artifact version

.github/workflows/test_backend.yml, .github/workflows/test_database.yml, .github/workflows/test_dht_node.yml, .github/workflows/test_e2e.yml, .github/workflows/test_federation.yml, backend/package.json, backend/yarn.lock, database/migrations/0044-insert_missing_contributions.ts, database/package.json, database/src/clear.ts, database/src/config/index.ts, database/src/index.ts, database/src/prepare.ts, database/yarn.lock, dht-node/package.json, federation/package.json
- update migration script, it checks first for db version before running all the migrations
- use tsx rather than ts-node for running ts code directly in database module
- prevent calling reset db in production
- use distinct databases for tests
- optimize github worker scripts
=> refactor(database): faster db version check

frontend/src/components/GddTransactionList.spec.js, frontend/src/components/GddTransactionList.vue, frontend/src/graphql/transactions.graphql, frontend/src/layouts/DashboardLayout.spec.js, frontend/src/layouts/DashboardLayout.vue, frontend/src/pages/Community.vue, frontend/src/pages/InfoStatistic.vue, frontend/src/pages/Send.vue
- remove hardcoded 1.5 seconds wait time for skeleton after finishing the loading of the transaction list 
- combine transaction list and user count request
- remove unnecessary reload call of transaction list on GddTransactionList, InfoStatistics and send
=> refactor(frontend): show skeleton only as long as needed
